### ISSUE TITLE
Payout curve should get all the accumulated funding fees

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1175]
One thing I noticed that is not directly related to this PR - but since we are adding the accumulated fees here it might be relevant:

Currently we pass the funding fee for *one* interval into rollover:

https://github.com/itchysats/itchysats/blob/28f7fa1836c12716a0595b862574204669dffbe8/daemon/src/model/cfd.rs#L724-L737

Is this correct in the context of accumulated fees - should it be `current_funding_fee + accumulated_previous_funding_fees` instead? 
How is the fee bucket managed - does the payout curve expect the accumulated fees, or just the fee for the last interval?

_Originally posted by @da-kami in https://github.com/itchysats/itchysats/pull/1170#pullrequestreview-858902780_

**Comment by da-kami** [comment]
We should actually pass in all fees, i.e. `fee_to_pass_to_payout = current_funding_fee + accumulated_previous_funding_fee + opening_fee`. 
That is, because the `opening_fee` is currently part of the internal bookkeeping and relevant for the payout calculation. 

Once we treat the `opening_fee` as separate output of lock (direct from taker to maker) we would change that. But that is not part of this ticket.

**Comment by thomaseizinger** [comment]
Adding this to the milestone as it is pretty important to sum these fees together.

**Comment by klochowicz** [comment]
Done as a part of #1170 ? @thomaseizinger @da-kami  is there anything else in this ticket?
