### ISSUE TITLE
Funding fee calculation panic

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1231]
I am getting this when creating a new CFD after taking the maker's offer:

```
2022-01-27 05:35:22 DEBUG daemon::model::cfd: Calculating funding fee using: margin 0.00136166 BTC, funding_rate -0.000339 and interval 24 order_id=1ea23cab-04fd-4cdb-a119-53e98ddd167b
thread 'rocket-worker-thread' panicked at 'values stored in db to be sane: Failed to represent as u64', daemon/src/model/cfd.rs:475:10
```

First line was added by me for debugging. 

Importantly, this panic kills the `taker_cfd::Actor`, which is never restarted unless we restart the whole daemon.

This was tested on b79b52d0a08fb33fc97deb38d93e591373ce69b1, which does not include #1217. This problem may disappear with that PR.

**Comment by da-kami** [comment]
Not sure it will disappear because I did not really change these calculations, just re-arranged them. Could you write a test against `fund-fund-fund`'s  `initial_funding_fee` function:

https://github.com/itchysats/itchysats/blob/c6ae9dd69f824a4b1beb82b264a308df2567f330/daemon/src/model/cfd.rs#L1344-L1357 

with the values of your CFD (hopefully known...) to ensure it does not panic?

**Comment by da-kami** [comment]
You can also just write a test again `calculate_funding_fee` with these values to see if you can reproduce the panic in a test please!

**Comment by da-kami** [comment]
I think this should be close with #1233
