### ISSUE TITLE
Cleanup the Cfd states in the projection to reduce decision logic in the UI

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1314]
We keep adding decision logic to the UI based on "old" states that are constructed in the projection. 
We should rather refactor the projection API to only expose Cfd states that are actually relevant for the UI to display.

## Annoyance counter

- 24/03/2022: Having to reason about these states in every client leads to bug where two clients can disagree on when a CFD is "closed". In particular, a CFD with the state `CollaborativeSettlementAccepted` is _not_ yet closed because we don't have the taker's signature yet.
- 29/03/2022: This topic came up again in a different context: https://github.com/itchysats/itchysats/issues/1701
- 29/03/2022: Incrementing counter to account for this duplicate: https://github.com/itchysats/itchysats/issues/960

**Comment by thomaseizinger** [comment]
I know @klochowicz has some opinions on this so please chim in with your view!

When re-designing this we should consider the following:

1. Automated clients care about the CFD's state _to some degree_. Primarily they care about whether or not the CFD is "open" or "closed". I put it in quotes because we haven't unambiguously defined what those terms mean. I'll have a go at that here:

A CFD is closed if the payout ratio has been determined and will never change again. In blockchain terms, this is equivalent to having a fully-signed and ready-to-be-broadcast transaction that spends the joint-output into two individual ones, one owned by each party. In any other case, the CFD is considered open.

I think the best way of representing this is with a boolean flag in the response: `is_closed`.

2. User-facing clients may also care about the CFD's state. However, this is has historically been a point of debate. In an ideal world, I think they shouldn't. Here is why:

- Assuming a "combined" position, a CFD is open if you are either long or short with some number of contracts. In blockchain terms, this means you have an unspent DLC somewhere on the chain. This is in-line with being exactly the inverse of the above definition.
- A user can in principle perform two operations: buy more contracts or sell some of their contracts. A user can always do that, even if they don't currently have a position. Not having any contracts and selling some = going short. Selling all your contracts = closing your position, etc. In this mental model, there is no notion of "state". All actions are available all the time.
- With CFDs being perpetual, the software has some internal states where the rollover protocol is active. What that exactly means in the long-run (see https://github.com/itchysats/architecture/pull/8) is not yet defined but what I would want to focus on is that they are internal states. We do of course somehow have to communicate to the user that their position is perpetual and has ongoing costs. However, I think that moving towards a rollover protocol that for example defines fixed funding periods similar to BitMex and where the point in time _when_ the rollover communication happens is randomized over the funding period would eliminate the need to expose this internal state to the user as well.
  We can clearly explain in the UI, when the perpetual costs are due without exposing the internal states of when we are sending messages to the maker to make that happen.

Concluding from this, I would propose that the notion of a `CfdState` as we currently have it is not something that should in any way be user facing. We may not yet be able to transition away from it immediately and may have to do it piece-wise but I think we should work towards getting rid of it from our public API.

**Comment by bonomat** [comment]
This is not really actionable. Feel free to reopen and refine the description.
