### ISSUE TITLE
collaborative close failed: collab_settlement_maker::Actor actor is down

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1361]
Is this an error? 

```
{
  "timestamp": "2022-02-04T22:38:45.888795251Z",
  "level": "WARN",
  "fields": {
    "message": "Collaborative close failed: collab_settlement_maker::Actor actor is down",
    "order_id": "08cf9246-8a84-4066-bcd8-153803be5467"
  },
  "target": "daemon::model::cfd"
}
```

**Comment by da-kami** [comment]
This can happen upon:

1. Restart if you were in a collaborative settlement before restart and it was not finished. (when you restart the actor is down)
2. If you did not accept/reject the collab settlement within 30 secs, because then the collab settlement actor will timeout and if you then accept/reject then the actor will be gone. In this scenario I think we log a timeout message, you could check if you see that one before you see the failure.

When did you see this? After a restart or during operation when triggering a collaborative settlement?

**Comment by da-kami** [comment]
Note: This is not critical, the `Cfd` will just remain open and you can trigger the collab settlement again. (It's annoying that we don't provide feedback that it failed in the UI, besides just transitioning back to open...)

**Comment by thomaseizinger** [comment]
Closing in favor of https://github.com/itchysats/itchysats/issues/1595. With a multiplexed transport, this problem cannot happen because it is impossible to send messages over a substream that no longer exists.
