### ISSUE TITLE
Improve the Taker UI to allow going short

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1422]
Initial version of going short in the taker's UI. 

 - tiles should show the Position (Long / Short)
 - at the very least we need 2 different prices (perhaps price on the button again?)

open questions hopefully solved by this task:
  - does it make sense to be able to go long and short at the same time?
  - is the UI still understandable with the new additions or we need some bigger redesign?

note: this task is not blocked by the backend, could initially show a dummy price in the UI.

**Comment by da-kami** [comment]
My thoughts on approaching this:

For extending the UI to short I would have suggested to just add the minimal thing possible and then see where we go from there:

I would assume for now:

1. The margin will be the same for going long/short
2. The fees for now will be the same as well. The funding rate will decide if we have to pay fees or receive (positive funding rate => long pays short, negative => short pays long). If we decide to have an opening fee (taker => maker) then the required bitcoin for opening the position might be different for long and short.
T
hat said: I don't think we have to let the user chose long/short beforehand. I think it can be the way is it, but there have to be two different prices for long and short. The Confirm dialog might display different fees for long and short (but by then we know which button the user pressed). The only downside of that is, that the fee structure is only visible once a button is clicked, but I'd accept that for now.

The minimal things that have to be done:

1. We need two maker prices in the UI (bid and ask price that define the price for going long and short), we could just add the respective price to the button again and remove the blinking maker price.
2. The tile has to show the position somehow
3. How do we want to display liquidation price for short positions for the taker?

I'd just do that and then see how it feels when using it. Then we can decide to do more changes if necessary.

**Comment by da-kami** [comment]
## Thoughts

Given that there will be two prices, the `required margin` will also be different for long and short, which somehow makes it hard to use what we currently have. 

We can either 

1. extend the display to have two required margins (one for short and one for long), or we 
2. have to add an additional choosing step for the user to decide going long or short.

If we go for (1) then we have to be aware that handling our `not enough balance` message will can't just be one message. We could work with disabling the button there and add a tooltip to the button why disabled, or add a message to the displayed `required margin` if the balance is not sufficient. 

If we split up the trade screen in long and short one easy way would be tabs. 

## That said. I propose...

I 'd propose to do the simplest thing possible to get the UI working, and role with extending the display that is currently there (i.e. solution 1 from above). Then we can test and see how it feels and if we need / want more changes. Here are the changes I propose:

1. Remove the blinking maker price.
2. Add the makers bid/ask price to the Long/Short button again (the price for going long and short is different)
3. Display `required short margin` and `required long margin`
4. If the balance is insufficient for either of the required margins, disable the respective button. Potentially remove the balance warning for now.
5. The confirmation screen might need some adapting, because the fee will be different depending no the funding rate (positive funding rate => long pays short, negative funding rate => short pays long)
6. The tile has to show the position

In the tile we will need the liquidation price for short as well, at the moment we always calculate `long`. I don't think this has to be tackled as part of this ticket though. @klochowicz what do you think?

**Comment by thomaseizinger** [comment]
Would a tab system for long and short be so much work?

**Comment by klochowicz** [comment]
IMHO a tab system would not be a good idea for such a simple operation....there's literally so much empty space right now.  anyway, the purpose of the task was to get something quick running and then iterate on it to find what seems to be the best result - we could try out tabs later on!

**Comment by da-kami** [comment]
This was done with #1552 and #1562
