### ISSUE TITLE
Mitigate sending out stale offers due to missing offer update

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1592]
With the recent change of automatically re-broadcasting offers from the given parameters, it can happen that the price gets stale if the automation fails to provide a new one.

Suggestion solution:

Extend the offer params endpoint with an "expiry" timestamp. The daemon is allowed to re-broadcast offers based on these parameters until that timestamp and has to stop otherwise. This ensures that - in case the automation fails to provide updated offer parameters - we stop sending out offers eventually.

**Comment by klochowicz** [comment]
an alternative way, arguably cleaner: the automation should be smart enough to adjust the `OfferParams` to withdraw the prices if they got stale by setting them to `None`.

**Comment by thomaseizinger** [comment]
The path on which we got to this problem was that the automation somehow failed internally and stopped updating the `OfferParams`. In that case, any logic that would detect a "stale" offer would likely also not have worked.

**Comment by klochowicz** [comment]
still, it sounds to me like an automation bug that could be fixed there! We could look at the timestamp of the offers when looking at them and prompt a refresh at certain interval (or at least triggering some error if they didn't get updated for longer). Right now the automation doesn't even verify that an offer got publish / updated at all on the feed.

**Comment by thomaseizinger** [comment]
Yes, it is a bug that can & should be fixed there. However, I think the proposed solution is still an improvement worth having because it makes client implementations simpler.

Any state that we don't need to keep track of in the client is good. Passing an expiry timestamp to the offer params allows the daemon to reason about these parameters without another interaction of the automation. Requiring the automation to follow up with this is tedious to implement and error prone. I'd rather empower the daemon to do this reasoning itself. This goes towards https://github.com/itchysats/architecture/issues/17.

Additionally, we can extend the implementation to automatically withdraw sent out offers from takers if that expiry timestamp is hit. We currently don't do that which is dangerous because it means an offer is basically valid forever.

**Comment by thomaseizinger** [comment]
@klochowicz What is your latest take on this issue? Are you strongly against the proposed solution or can we implement it as described and see how it performs?

**Comment by klochowicz** [comment]
I feel like this proposal goes against ADR003 - for me this is a concern of the automation / UI. Furthermore, this makes the maker implementation *less simple*.

As for the rest of the arguments, you don't need to keep track of timestamps or anything really - if you don't get price updates for X seconds, the client should send `None` immediately to indicate that it can't figure out new price. This makes things simple and robust IMHO.

**Comment by klochowicz** [comment]
That said, I don't mind a *short-term* fix until we fix automation if we don't trust it to react (until we make it more robust) :-)

**Comment by thomaseizinger** [comment]
> I feel like this proposal goes against ADR003 - for me this is a concern of the automation / UI. Furthermore, this makes the maker implementation _less simple_.

If this proposal violates ADR003, wouldn't the original change of immediately sending out a new offer also already violate that decision?

The concept of a TTL is fairly design component and IMO naturally fits this problem. If we delegate the power of sending out new offers to the maker, why not also tell it in one go, when to stop doing that?

**Comment by klochowicz** [comment]
I don't think it's the case, because the *decision* to start/stop the flow of offers lies outside the maker - I see it more like an ergonomics change.

to me adding TTL here feels like a hack because we are not in any place at the time to perform a guess when sending out an offer (unless bitmex is actually sending us TTL of their price feed?). The correct answer for this question for me is "until the price feed gets stale".

Again, I'm happy for this to come through if this will plug a hole and buy us some time until we make automation more robust!

**Comment by thomaseizinger** [comment]
> to me adding TTL here feels like a hack because we are not in any place at the time to perform a guess when sending out an offer

I think we are totally in place to make that decision. ADR003 specifies that an outside component like an automation bot is in charge of the business rules around price making like spreads etc. Those decisions are associated with how much risk you want to take in regards to volatility of the market and whatever you want really.

Being able to provide a TTL together with a price a form of managing this risk. It is saying: "Here are some offer parameters and I am confident that my underlying trading strategy will be profitable with this parameters for the next 2 minutes." If the market changes, new parameters are handed over. If the market doesn't change, you need to still refresh them. If for any reason, we are not able to refresh them, the TTL provides a safety switch to stop trading _precisely because the daemon is in no position_ to make a decision on whether the current offer parameters are any good.

Now that I think about, I'd say this is actually perfectly in line with ADR003.

**Comment by klochowicz** [comment]
The reason I dislike this is that this business decision can be achieved already by the existing API, and achieving the same thing by multiple ways in an API is not a good design practice.

You can do precisely that strategy with the current API, because there are means of withdrawing offers when the risks become too much.

**Comment by thomaseizinger** [comment]
> The reason I dislike this is that this business decision can be achieved already by the existing API, and achieving the same thing by multiple ways in an API is not a good design practice.

I see that point and I agree with it.

> You can do precisely that strategy with the current API, because there are means of withdrawing offers when the risks become too much.

What if that is not possible because the automation bot dies for example? There is a risk in that as well.

**Comment by bonomat** [comment]
> to me adding TTL here feels like a hack because we are not in any place at the time to perform a guess when sending out an offer (unless bitmex is actually sending us TTL of their price feed?). 

Re bitmex TTL: Bitmex price feed does not have a TTL because it does not give you any guarantees about the price. On the contrary, it's logical that it can't because it is a marketplace and not a centralized broker. 
The price we get from Bitmex might have never been a "real" price neither: we get the 1 minute bucket price which is the average of the bids/asks at a specific minute. Bitmex updates this price every minute. 
So, I don't think you can compare these two things :) 

> The correct answer for this question for me is "until the price feed gets stale".

Some time ago we added this feature where we resend the same order again if an offer was accepted or rejected. Would you remove this? 

Personally, I would add a TTL and leave the current behavior. Imho this is a good feature to have, as also the taker can make use of this feature: I can only take an offer within the TTL

**Comment by da-kami** [comment]
Note: Some mitigation achieved by #1658 
We also found the bug in the automation and fixed it https://github.com/itchysats/maker-automation-rs/pull/88

We should still evaluate ensuring sanity in the maker daemon.

**Comment by bonomat** [comment]
Does not happen at the moment.
