### ISSUE TITLE
Use the current price for collaborative settlement and not the payout

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1608]
Originally we wanted to solve this the other way round, i.e. use the payout curve to determine unrealized P/L as described here https://github.com/itchysats/itchysats/issues/1184

However, it is a better UX to use the current price I think. And for collab settlement it should be possible.
Given that both parties have the same P/L calculation for the current price we can deterministically come up with the amounts on both sides. Correct me if I'm wrong.

**Comment by thomaseizinger** [comment]
Interesting idea. I think I could come around to this view.

Force-closing is the exception so we could do things differently in a collaborative setting.

The problem lies in how you design the protocol such that there is an agreement between both parties? I guess if we take the maker's price, the calculation would be exact.

**Comment by da-kami** [comment]
> Interesting idea. I think I could come around to this view.
> 
> Force-closing is the exception so we could do things differently in a collaborative setting.
> 
> The problem lies in how you design the protocol such that there is an agreement between both parties? I guess if we take the maker's price, the calculation would be exact.

What is the problem with deterministically calculating the precise output on both sides if the price is agreed upon?
At the moment the taker sends a price and amount to the maker that will be used. I think we should be able to deterministically calculate the exact payout based on that price without using the payout curve.

If we can't do that, then the assumption of calculating the margins, and even payout curve independently should be questioned as well, or am I missing something?

So what I'm saying is: The design would be the same, but the calculation would be pretty much the unrealized P/L calc with the price the taker sends as closing price (if that price is accepted by the maker). The maker calculates the amount and compares it against the amount the taker sent. If matches: close using the amount, otherwise, reject...

**Comment by thomaseizinger** [comment]
> > Interesting idea. I think I could come around to this view.
> > Force-closing is the exception so we could do things differently in a collaborative setting.
> > The problem lies in how you design the protocol **such that there is an agreement** between both parties? I guess if we take the maker's price, the calculation would be exact.
> 
> What is the problem with deterministically calculating the precise output on both sides **if the price is agreed** upon?

Yes, once there is an agreement on the price, it is easy. Like I said, the difficulty is in agreeing on the price IF there is ambiguity in what the price should be.

> (if that price is accepted by the maker)

"Collaboratively settling" is equivalent to selling your contracts to the maker. You can only sell based on an offered price (otherwise you are offering and are essentially the maker). Given that, I think the (current) idea of a price being acceptable to the maker is flawed. We have that price available as part of the offer now that the taker can go short.

Instead of sending a price, referring to the bid price of the latest maker offer would make the notion of an "acceptable price" disappear. Going one step further, with a combined position, this problem wouldn't exist at all.

**Comment by bonomat** [comment]
Closing this in favor of https://github.com/itchysats/itchysats/issues/2924
