### ISSUE TITLE
The UI keeps rendering even though there is not state change

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#165]
The UI keeps randomly refreshing upon receiving feed updates. 

This can have awkward side effects, examples:

* When applying sorting to a cfd table the sorting is randomly reset

I don't think that the UI should re-render that often, there is no state change.

**Comment by bonomat** [comment]
> I don't think that the UI should re-render that often, there is no state change.

I noticed this as well. The time of the wallet changes regularly 😅

**Comment by thomaseizinger** [comment]
> > I don't think that the UI should re-render that often, there is no state change.
> 
> I noticed this as well. The time of the wallet changes regularly sweat_smile

That is expected! The idea is that the user is made aware that we are actively syncing in the background.

To debug undesirable re-renders, I can recommend the React Dev Tools extension. I had a quick peek yesterday and it seems it is being caused by some of our hooks changing. Haven't looked into it further though ...

**Comment by bonomat** [comment]
The table refreshing issue is explained here: https://react-table.tanstack.com/docs/faq#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes

In a nutshell, the table resets its state if the data changes. 
I've fixed this in #207 if there are other unwanted state changes please mention it.
