### ISSUE TITLE
Figure out, how to actually leverage an empty events table for performance improvements

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1771]
Once https://github.com/itchysats/itchysats/issues/1651 is landed, the `events` table will be empty if a node has 0 open CFDs.

In that state, a software upgrade that changes the structure of the events is safe. We can leverage this to make backwards-incompatible changes to the layout of our events either for reasons of performance improvements or otherwise.

The tricky part that we need to solve is: How do we get the users application into this state?

Some ideas (with varying degree of user experience):

1. The application could detect that it is about to run a version with incompatible events for the first time, force-close all CFDs, wait until they are completely closed and only then initialise the user interface.
2. The application could refuse to boot if the events table is not empty, thus forcing the user to close all CFDs prior to the upgrade with an old version.
3. Assume (2) and force-close all positions through the maker whilst at the same time, not allowing new positions to be opened. Release a new version once there are no open positions.
4. Introduce a new version of the events we want to change, keeping the old ones working. Track _per CFD_ which software version it was opened with. Monitor how many open CFDs we still have with this software version. Release new version that removes old events once those CFDs drop to 0 or some defined threshold.

**Comment by thomaseizinger** [comment]
I though about this a bit more.

We can actually make changes to the events _today_. They just need to be backwards-compatible. We can achieve that by introducing new events and mapping the old events to new ones. For that, it would probably be wise to introduce a dedicated `db::Event` type that deals with serialization and have the `model` layer not care about serialization at all. Then the `db` module can keep supporting old events and map into the newest representation.

When we can remove support for these old events is actually a completely different problem and does not need to be solved straight away. The only downside of that is some legacy mapping code that will be around for a while.

Once we have shipped a few releases with the mapping code in it, we can always make a judgement call on when we think it is safe or acceptable to remove it. To not break any users at that point, all their CFDs will have to be closed.

**Comment by da-kami** [comment]
> We can actually make changes to the events today. They just need to be backwards-compatible. We can achieve that by introducing new events and mapping the old events to new ones. For that, it would probably be wise to introduce a dedicated db::Event type that deals with serialization and have the model layer not care about serialization at all. Then the db module can keep supporting old events and map into the newest representation.

I like this proposal. I think we should aim for this.
Yes, it would be great if we could keep the mapping purely in the database layer, and the model changes (without introducing model versions). I would hope that our changes will allow that. We can then easily have versioned tables in the db as well, and map old CFDs in the new model.

If we cannot achieve to map old CFDs into the new model I think we should go for a breaking version that forces users to close all positions before an upgrade. We would have to define details for the upgrade process though.
I feel having multiple model version will add complexity that we don't want at the moment.

**Comment by bonomat** [comment]
I find it a bit hard to reason about a generic upgrade solution without knowing what we want to change. 
Imho a solution depends on the exact changes we want to introduce and any of the proposed 4 points might be viable depending on the scope of the change.

The proposed solution of mapping old events onto new events sounds to be the least invasive one with the best user experience :)

**Comment by bonomat** [comment]
# What do we want to optimize

We want to lower the storage/db size and want to reduce the time to load CFDs from the DB. 

## Why is the DB so big

We store every event. The biggest events are `ContractSetupCompleted` and `RolloverCompleted` because both store the whole `DLC` including all `CETs`. With our current config of 200 CETs one of these events has roughly `820kb`. In the long run I see more CETs being used to have a finer granularity on the payouts. This is important if the amounts are bigger. Hence, the size of this will grow!

A rollover happens ideally 1/h meaning for a single CFD we have ~`24*820kb=20mb` in data per day!

Our rollover protocol foresees that a user should never publish an old state, i.e. if a rollover was completed, a user should not publish an old state. 
Publishing an old state can either be a mistake (our famous problem of a rollover worked for one party but not for the other party) or a malicious attempt: the user wants to publish an old state to profit from it. 
Since we can't distinguish these situations easily, the user should be _punished_ if he published an old state. 

For punishment we need a few things from passed rollovers: 
- encsig (our own)
- revocation secret (other party)
- publication keys (other party)
- txid of the old transaction
- the spending script

We don't need: 
- the old CETs which are the biggest part of the data

## What can we do?

With #1779 landed we move closed CFDs into their own table and delete all events. This frees storage and speeds up loading time. 

However, this does not optimize open positions. A single position being open for a year will have ~ `7.3GB` in storage. 
Hence, we need an additional solution: 

### Snapshots

Snapshots have been discussed various times: they allow us to store a snapshot at a specific point of time and hence optimize loading - we don't need to load the whole history of events but can start from the snapshot. 
While contradicting with the core idea of ES this would also allow us to delete old events prior the snapshot to free up storage. 

The question is, how often do we snapshot: 

1. time-based snapshots: We can do a snapshot 1/day, 1/hour/, ... The challenge I see here the longer we wait, the larger and more costly it gets to load everything and create a snapshot. If it is too often, even if it is fast, it will result in spikes in machine resources and might block the DB unnecessarily. 
2. Snapshot after an event: We could do a snapshot after specific events, since the only regular events we are having are rollover-events, we could do a snapshot after each rollover. This should be relatively fast and cheap. The question is, do we even need the old events anymore? We will always base our business logic on the latest snapshot, all prior events are not important. 
3. Snapshot after X events: We could do a snapshot after X rollover. The hard part is to get X right, the more users we get, the smaller the X should be going eventually closed to solution 2. 

Our goal is to scale big, it may take some time, but eventually we will get there. 
In numbers expressed, if we have 1000 users and increased our CETs to 5MB (~1k CETS), we will have `5GB` of data every hour. We basically have to do snapshots after each event because we can't optimize much more. 

The only way out is to do rollovers less often but this will only push the inevitable a bit away.

That being said, is this a sign that we should drop ES hard rules on immutability? 
If we have todo a "snapshot" after each event, are we even following the core ideas of ES?
