### ISSUE TITLE
Fetch announcements dynamically from Olivia

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#185]
At the moment, we are fetching announcements based on URLs built on the client side. Instead, we should be querying Olivia for the available announcements and dynamically build them based on the response.

**Comment by luckysori** [comment]
Which part of the request should be dynamic? At the moment we are building it as such:

```rust
format!("{}x/BitMEX/BXBT/{}.price[n:20]", OLIVIA_URL, datetime)
```

I don't think the time can be dynamic because the values go from way in the past to way in the future

![image](https://user-images.githubusercontent.com/9418575/136479907-5a343b37-1be6-4778-b4d1-4b4418db0a33.png)

You could verify that your intended value exists in the range, but you need to know it ahead of time i.e. you can't rely on the boundaries of the range.

You could theoretically get the `price[n:20]` section from `olivia` if each price event were indexed by the number of nonces, but the response looks like this:

```json
{"events":["price[n:20]"],"children":{"kind":"list","list":[]}}
```

Is it worth looking in the list of events for the string that contains `20` and then fetching the corresponding event?

**Comment by thomaseizinger** [comment]
I think mostly the number of nonces.

I remember @llfourn having an opinion here so I'll let him comment.

**Comment by LLFourn** [comment]
Ok so here's the way of thinking about it given what you hardcode:

`/` - nothing is hardcoded app can deal with any event
`/x` - You are only dealing with exchange rates and prices.
`/x/BitMEX` - You are only that you are dealing with exchange rates and prices on BitMEX.
`/x/BitMEX/BXBT` - you are only dealing with `BXBT` on BitMEX.

It's fine to hardcode the above. Furthermore it's fine to hardcode the fact that after BXBT will come a UTC datetime (sans Z) because that's the conventional structure of things after `/x`. 
If you query `/x/BitMEX/BXBT` you will get this:
```
$ curl https://h00.ooo/x/BitMEX/BXBT|jq
{
  "events": [],
  "children": {
    "kind": "range",
    "range-kind": "time",
    "interval": 3600,
    "start": "2021-10-08T01:00:00",
    "next-unattested": "2021-10-11T02:00:00",
    "end": "2022-01-09T01:00:00"
  }
}
```
Note the breaking changes I've just made to it: start, end no longer objects and next-unattested exists now.

So now the question is do you hard code the interval as 3600 (or at least that whatever the interval changes to in the future will divide 3600)? That's fine I guess -- it would only be a problem if I decrease the frequency to every 2 hours or every day. Maybe you'll want your app to be able to configure the CFD to different time intervals or different oracles in the future though in which case you should fetch it dynamically. 

The next question is do you want to hard code the event kind, in particular the number of nonce parameter?

```
$ curl -sL https://h00.ooo/x/BitMEX/BXBT/2021-10-11T02:00:00 |jq
{
  "events": [
    "price?n=20"
  ],
  "children": {
    "kind": "list",
    "list": []
  }
}
```

Well assuming that project hermes succeeds and causes another super bull run by itself this number will likely not be enough in a year. I will have to increase it on `h00.ooo` for future events. In which case hermes will break and make people lose confidence and cause a multi-year bear market. So I think you should not hard code "20" in there but fetch it dynamically.

[EDIT] @thomaseizinger suggested olivia could do better by using proper links to describe the "resources". I actually used to do that (well not links by full absolute paths) and am ready to here design ideas. 

The reason I changed it was I was concerned with strictly navigating things like a directory (only being being able to descend). This was to keep as little trust in the oracle as possible because it could not send you somewhere unrelated to where you were initially. Perhaps this is pedantic.

**Comment by thomaseizinger** [comment]
Likely the way we are currently doing this is fine.
