### ISSUE TITLE
Re-work funding rate to display positive when the user is getting paid and negative when the user pays

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1877]
### Discussed in https://github.com/itchysats/itchysats/discussions/1751

After a discussion on github, I think we're pretty aligned how we want to represent the funding rates:
- negative, if the user is paying (funding)
- positive, if the user is getting paid (getting funded)

The proposal in the discussion to just expose the correct API from the daemon (as it knows the role) seems sensible. @thomaseizinger posted some name suggestions in the discussion (https://github.com/itchysats/itchysats/discussions/1751#discussioncomment-2497443)

<div type='discussions-op-text'>

<sup>Originally posted by **bonomat** March 27, 2022</sup>
The way how funding rate is depicted at the moment might be confusing. 
I know that a positive funding rate means, long pays short but this is not really visible nor described anywhere. 
Right now, it looks like that both, longs and shorts will need to pay this rate: 

--- Annoyance Counter --
(1) Discussion started: https://github.com/itchysats/itchysats/discussions/1751
(2) Discussion point 1: team members are confused https://github.com/itchysats/itchysats/discussions/1751#discussioncomment-2497441
(3) Discussion closed and started working on [#1877](https://github.com/itchysats/itchysats/issues/1877)
(4) Wrote an ADR which showed that team members are not aligned on what it actually means
(5) New ticket created which looks like a UI Bug: https://github.com/itchysats/itchysats/issues/2107
(6) It's really hard to figure out if the numbers in our UI are correct.

**Comment by bonomat** [comment]
Note: I started with what was proposed in https://github.com/itchysats/itchysats/discussions/1751#discussioncomment-2497443 but came to the conclusion that this does not add as much value as expected: 
- we have four fields instead of two
- we would need to check for `null` or `undefined` in the UI to know if the taker has to pay or will be paid

The initial attempt can be seen here: [#3e9621f792ea044fc00c033c88c084accd32bdd9](https://github.com/itchysats/itchysats/commit/3e9621f792ea044fc00c033c88c084accd32bdd9)

instead, I opted for changing funding rate to interest rate and fix the sign according to the taker's position.

**Comment by bonomat** [comment]
This project is unmaintained
