### ISSUE TITLE
rollover happening every two hours

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1974]
This sounds like a bug in mainnet-v0.4.12 

We found that my taker is rolling over orders every 2h but asks for `hours_to_charge`:1`

```
{"timestamp":"2022-05-06T00:03:04.677445035Z","level":"DEBUG","fields":{"message":"Accepting rollover proposal","order_id":"8a21b8cc-4dc4-4dc8-a4be-3122f762154e","rollover_version":"V2","hours_to_charge":"1","funding_fee":"0.00000001 BTC"},"target":"model::cfd"}
{"timestamp":"2022-05-05T22:03:04.0474127Z","level":"DEBUG","fields":{"message":"Accepting rollover proposal","order_id":"8a21b8cc-4dc4-4dc8-a4be-3122f762154e","rollover_version":"V2","hours_to_charge":"1","funding_fee":"0.00000001 BTC"},"target":"model::cfd"}
```

**Comment by bonomat** [comment]
Additional note: 

My taker is sending **two** rollover proposals at the same time.

**Comment by luckysori** [comment]
### Analysis

After some time investigating this, this is what I have figured out:

- A CFD is eligible for extension via rollover as soon as the settlement time is 23 hours in the future or less:

https://github.com/itchysats/itchysats/blob/3bc975548c05eb141fe61724625393839d134cb4/model/src/cfd.rs#L787-L797

- We check for rollover eligibility every 5 minutes:

https://github.com/itchysats/itchysats/blob/3bc975548c05eb141fe61724625393839d134cb4/daemon/src/auto_rollover.rs#L140-L144

- Combining the first two points, we expect most CFDs to be rolled over when the settlement time is between 23 hours and 22 hours and 55 minutes in the future. Since BitMEX event IDs are based on whole hours, it follows that the timestamp at which rollover is expected to be triggered should have a value of 0-5 for the minutes.

- When we perform a rollover, we set the new settlement time between 24 and 25 hours in the future, as can be seen here: 

https://github.com/itchysats/itchysats/blob/3bc975548c05eb141fe61724625393839d134cb4/maker/src/rollover.rs#L175-L176

where `interval` is always 24 hours.

- The `next_announcement_after` API returns an event ID with a timestamp close to 25 hours whenever the current timestamp (i.e. the value returned by calling `OffsetDateTime::now_utc`) has low minutes.

I think this explains why most rollovers happen every 2 hours.

### Solution

There is no inherent problem with rolling over every 2 hours. For a while we have been charging/paying the funding fee according to the number of hours by which the settlement time is to be extended.

The real problem lies in the fact that the BitMEX event ID timestamp we choose does not match the one predicted by the function we use to calculate the number of hours to charge for when rolling over: `hours_to_extend_in_rollover`.

In order to fix this mismatch I propose to use the value returned by `next_announcement_after` when calculating the `hours_to_extend_in_rollover`, as opposed to assuming that the next settlement time will always be 24 hours away.
