### ISSUE TITLE
Initial Funding Fee should be negative?

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2107]
Our function `FundingFee::calculate` computes the _funding fee_ based on the counter party's amount: 

https://github.com/itchysats/itchysats/blob/20bfc556eebfcf9e55a617ef78b0cc72ded16e6e/model/src/lib.rs#L691-L733

The amount returned here is always positive.

which in return leads to the front end displaying the amount as always being positive. 

Even though the funding rate is negative, the amount is positive. 
Do I have to pay or will I get paid?

![image](https://user-images.githubusercontent.com/224613/170146624-d08e92e2-921e-4bc6-882f-8ad66688c3a4.png)

Related to: #1751

**Comment by bonomat** [comment]
Labelled this as a UI bug as I think it's wrong.

**Comment by da-kami** [comment]
From the top of my head: 
`Funding for first 24h` is a `fee` so if it is positive it has to be paid, if negative we receive it. 
If you go short with a negative rate it should be positive because `short pays long`.

I think this is correct, but I agree that it is confusing.

At the moment the funding rate is positive and in the `Confirm` dialog I see a positive value for going long and a negative one for short.

**Comment by bonomat** [comment]
Thanks for the clarification. Closing this at it seems correct.
