### ISSUE TITLE
Stream ended abruptly whilst waiting for maker decision on collab-settlement

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2255]
The maker disagrees with the taker on the settlement. This can happen, but the error we emit on the taker side lead us to think that our connection was faulty (because the stream ended abruptly). The connection is fine in this instance.

We may want to emit a rejection from the taker side instead of failing, but this is all debatable.

[Grafana logs here](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22,%20container%3D~%5C%22taker_master%5C%22%7D%20%7C%3D%20%60End%20of%20stream%20while%20receiving%20Decision%60%22,%22queryType%22:%22range%22,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22,%20container%3D%5C%22maker%5C%22%7D%20%7C~%20%60Failed%20to%20start%20collab%20settlement%20protocol%60%20%7C%20json%20%7C%20level!%3D%60DEBUG%60%22,%22queryType%22:%22range%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221655420177927%22,%22to%22:%221655436365626%22%7D%7D).

**Comment by klochowicz** [comment]
A bit more background: 
we have added an additional check that we would come up with the same transaction on both sides (since both parties now try to publish it):

https://github.com/itchysats/itchysats/blob/master/model/src/cfd.rs#L1064

In the logs above, the transactions were not the same (off by 1 sat), so the maker decided to shut down the protocol (currently we emit failed in such situations, as it was not a manual rejection).

I will seek to create a github discussion / ADR to decide whether this should be treated as a rejection instead. 

What is clear though, it is not caused by libp2p layer, but rather by the changes in the underlying protocol.

**Comment by luckysori** [comment]
We're no longer experiencing this.
