### ISSUE TITLE
Read from empty / terminated substream

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2262]
Note: We use a fixed time interval for most of the queries that roughly corresponds to the last 24h at the point the ticket was opened) so that the queries can be used at a later point in time as well.

1. [The taker fails to read `reject` decision from the maker](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20rollover%20decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D)
    * [This also happens for collab settlement](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20Decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D) - during the time interval where we used to reject short positions closure because of testnet/mainnet price diff [we saw this quite often](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20Decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655099490787%22,%22to%22:%221655173650191%22%7D%7D) (this is a query further in the past)

3. [The taker fails to read `Msg3` of a rollover](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22Rollover%20failed:%20Empty%20stream%20instead%20of%20Msg3%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D) (resulting in the parties having different rollover state)
   * [If you overlay taker and maker for the first case where this happens for `61836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1`](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655420142904%22,%22to%22:%221655420945279%22%7D%7D) then you see that the maker get s `Rollover was completed` and stops and the taker right at that spot runs into `Rollover failed` because of  it can't read `Msg3` because of `Empty stream`.

    * [Previously we had this problem on the maker side](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D~%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22Empty%20stream%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655325646302%22,%22to%22:%221655469956492%22%7D%7D) (but this flipped due to the changes in #2200 where the taker now is the last one that reads every time) - Note: The time-interval for this one is slightly longer than the other queries.
    * Also note that this is cause by the same [problem where we previously `panicked` due to `select_next_some`](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22Taker%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22276cd584-673d-406b-8764-c0f54478f6df%5C%22%20!%3D%5C%22Applying%20new%20events%20to%20CFD%5C%22%20!%3D%5C%22collab_settlement%5C%22%20!%3D%5C%22settlement%5C%22%20!%3D%5C%22Settlement%5C%22%20!%3D%5C%22settle%5C%22%22,%22hide%22:false%7D,%7B%22refId%22:%22Maker%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22276cd584-673d-406b-8764-c0f54478f6df%5C%22%20!%3D%5C%22Applying%20new%20events%20to%20CFD%5C%22%20!%3D%5C%22collab_settlement%5C%22%20!%3D%5C%22settlement%5C%22%20!%3D%5C%22Settlement%5C%22%20!%3D%5C%22settle%5C%22%22,%22hide%22:false%7D,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22panic%5C%22%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221655091899950%22,%22to%22:%221655100469321%22%7D%7D). `select_next_some` was only panicking because upon reading the last message we received a `Ready(None)`. In this query we overlay maker and taker and one can see that the timestamps of one appending `RolloverCompleted` matches the other party panicking.

4. [We see this problem when the taker processing offers from the maker as well](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D~%5C%22maker%7Ctaker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22The%20stream%20has%20terminated%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D)

In general this problem happens when the stream returns `Ready(None)` upon reading from it. This is unexpected behavior in our setup.

**Comment by da-kami** [comment]
My analysis led me to believe that the problem *might* come from this code block:
https://github.com/mxinden/asynchronous-codec/blob/master/src/framed_read.rs#L194-L209

that uses this code for `decode`: 
https://github.com/mxinden/asynchronous-codec/blob/master/src/codec/json.rs#L112-L133

I believe the problem could come from there because this is one of the only parts in the code where `poll_read` (following `next` downstream) can result in `Ready(None)`.

**Comment by luckysori** [comment]
>     1. [The taker fails to read `reject` decision from the maker](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20rollover%20decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D)

This is a duplicate of https://github.com/itchysats/itchysats/issues/2259. 

More info on the issue linked, but I'd like to clarify that this error has nothing to do with dropping streams after ending successfully on one side. The maker fails because of a newly added invariant. We could have a bug, but it has nothing to do with the new network stack.

@klochowicz provided [additional proof](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,level!%3D%5C%22TRACE%5C%22,level!%3D%5C%22DEBUG%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20rollover%20decision%5C%22%20%7C%3D%20%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%22%7D,%7B%22refId%22:%22C%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%20%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%20%7C%20json%20%7C%20level!%3D%5C%22TRACE%5C%22%20%7C%20level!%3D%5C%22DEBUG%5C%22%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221655420612558%22,%22to%22:%221655421181947%22%7D%7D). 
    
>        * [This also happens for collab settlement](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20Decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D) - during the time interval where we used to reject short positions closure because of testnet/mainnet price diff [we saw this quite often](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20Decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655099490787%22,%22to%22:%221655173650191%22%7D%7D) (this is a query further in the past)

This is a duplicate of https://github.com/itchysats/itchysats/issues/2255.

Again, this is not a case where one party finishes successfully and the other does not. In this case the maker disagrees with the taker's proposal (in the linked example by a single satoshi) and rightfully aborts the protocol. We could have a bug, but it has nothing to do with the new network stack.

@klochowicz provided [additional proof](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22taker%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20Decision%5C%22%20%7C%3D%20%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%22,%22editorMode%22:%22code%22,%22queryType%22:%22range%22%7D,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%20%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655423996383%22,%22to%22:%221655427685888%22%7D%7D).

>     2. [The taker fails to read `Msg3` of a rollover](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22Rollover%20failed:%20Empty%20stream%20instead%20of%20Msg3%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D) (resulting in the parties having different rollover state)
>        
>        * [If you overlay taker and maker for the first case where this happens for `61836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1`](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655420142904%22,%22to%22:%221655420945279%22%7D%7D) then you see that the maker get s `Rollover was completed` and stops and the taker right at that spot runs into `Rollover failed` because of  it can't read `Msg3` because of `Empty stream`.

This is, in our opinion, the only error that could possibly be related to the new network stack (and I'm still reluctant to believe that it actually is because there is no proof). We have only been able to analyse the linked example (there are no other examples of the very same error recently).

It seems like this could have been a freak incident, see [logs](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22taker%20reads%20from%20empty%20stream%20during%20rollover%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22Rollover%20failed:%20Empty%20stream%20instead%20of%20Msg3%5C%22%20%7C%3D%20%5C%22ERROR%5C%22%22%7D,%7B%22refId%22:%22maker%20fails%20to%20get%20announcement,%20closing%20stream%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221655420700000%22,%22to%22:%221655420880000%22%7D%7D). One can see that the machine failed to report logs for almost 1 minute _after_ it started the rollover and _before_ it succeeded. We could consider that the machine failing to report logs could be an indication that something went wrong, which could result in not being able to deliver our `Msg3` to the taker. It is very hard to analyse further. I would recommend to open a separate issue and monitor if we get any more of these errors on `testnet`.

>        * [Previously we had this problem on the maker side](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D~%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22Empty%20stream%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655325646302%22,%22to%22:%221655469956492%22%7D%7D) (but this flipped due to the changes in [Ensure message order at the end of rollover #2200](https://github.com/itchysats/itchysats/pull/2200) where the taker now is the last one that reads every time) - Note: The time-interval for this one is slightly longer than the other queries.

You have linked to logs which describe an error about _Msg0_. We have looked into this too, and it is apparent that this is also not related to the new network stack. It is an extremely similar situation to the issues described in your first bullet point: maker fails, aborts the protocol and closes the stream. Here are the [logs](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22taker%20reads%20from%20empty%20stream%20during%20rollover%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22Rollover%20failed:%20Empty%20stream%20instead%20of%20Msg0%5C%22%20%7C%3D%20%5C%22ERROR%5C%22%22%7D,%7B%22refId%22:%22maker%20fails%20to%20get%20announcement,%20closing%20stream%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221655460028000%22,%22to%22:%221655460050000%22%7D%7D).

In this case the maker fails to fetch the announcement, closing the substream. When the taker tries to read from it the stream is closed. This is acceptable behaviour that would be hard to improve unless we want to handle all possible errors with dedicated messages. I think closing the stream is a simple way of letting the other party know what something went wrong. They could just retry and it would probably work the next time.

>     3. [We see this problem when the taker processing offers from the maker as well](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D~%5C%22maker%7Ctaker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22The%20stream%20has%20terminated%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D)

This error also does not have to do with succeeding on one side, closing the substream and causing the other party to fail because of it. [Logs used](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22taker%20master%20offer%20got%20closed%22,%22expr%22:%22%7Bcontainer%3D~%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22The%20stream%20has%20terminated%5C%22%22,%22hide%22:false%7D,%7B%22refId%22:%22maker%20all%20logs%22,%22expr%22:%22%7Bcontainer%3D~%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%20json%22,%22hide%22:false%7D,%7B%22refId%22:%22taker%20master%20all%20logs%22,%22expr%22:%22%7Bcontainer%3D~%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221655397180000%22,%22to%22:%221655397360000%22%7D%7D).

In this case we appear to open a substream from the maker side to send out offers and later fail to negotiate the protocol with the other party because of a protocol negotiation timeout. The taker tries to handle the message, but it's too late so the stream is already gone. We should investigate this, because it seems weird that the taker gets the `NewInboundSubstream` despite the negotiation failing. But it is not critical (the stream could be dropped for whatever reason! After all these actors are supervised and we know they can be restarted from time to time) and it happened very rarely (we push new offers constantly).

**Comment by da-kami** [comment]
> This is a duplicate of https://github.com/itchysats/itchysats/issues/2259.

> More info on the issue linked, but I'd like to clarify that this error has nothing to do with dropping streams after ending successfully on one side. The maker fails because of a newly added invariant. We could have a bug, but it has nothing to do with the new network stack.

[This is not the only CFD that has these problems in the last 7 days](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20Decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655089944743%22,%22to%22:%221655437441678%22%7D%7D), we should validate that the source is the same problem.

For position `61836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1` we run into this problem because the previous rollover already failed -[I had linked that (this is the relevant failure)](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655420142904%22,%22to%22:%221655420945279%22%7D%7D). 
[If you look at all the data of the CFD concerning `Rollover`](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%20%7C%3D%5C%22Rollover%5C%22%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%2261836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1%5C%22%20%7C%3D%5C%22Rollover%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655404719717%22,%22to%22:%221655452101520%22%7D%7D) then after that initial failed rollover (taker fails, maker succeeds) all kinds of things are reported as problems - but those result out of the first failure and I don't think we have to put time into investigating consecutive failures if we can avoid the initial problem.

> [The taker fails to read reject decision from the maker](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20rollover%20decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D)

>    [This also happens for collab settlement](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20Decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655383568957%22,%22to%22:%221655469467880%22%7D%7D) - during the time interval where we used to reject short positions closure because of testnet/mainnet price diff [we saw this quite often](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22End%20of%20stream%20while%20receiving%20Decision%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655099490787%22,%22to%22:%221655173650191%22%7D%7D) (this is a query further in the past)

because those might be the result of the parties not agreeing on rollover state. We have to make sure this is true though. In the past we saw a lot of `Empty stream` upon collab close rejections due to price differences. I am not sure we can explain them with the same problem source.

**Comment by da-kami** [comment]
> >        * [Previously we had this problem on the maker side](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D~%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22Empty%20stream%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655325646302%22,%22to%22:%221655469956492%22%7D%7D) (but this flipped due to the changes in [Ensure message order at the end of rollover #2200](https://github.com/itchysats/itchysats/pull/2200) where the taker now is the last one that reads every time) - Note: The time-interval for this one is slightly longer than the other queries.

> You have linked to logs which describe an error about _Msg0_. We have looked into this too, and it is apparent that this is also not related to the new network stack. It is an extremely similar situation to the issues described in your first bullet point: maker fails, aborts the protocol and closes the stream. Here are the [logs](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22taker%20reads%20from%20empty%20stream%20during%20rollover%22,%22expr%22:%22%7Bcontainer%3D%5C%22taker_master%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22Rollover%20failed:%20Empty%20stream%20instead%20of%20Msg0%5C%22%20%7C%3D%20%5C%22ERROR%5C%22%22%7D,%7B%22refId%22:%22maker%20fails%20to%20get%20announcement,%20closing%20stream%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221655460028000%22,%22to%22:%221655460050000%22%7D%7D).

Sorry, it seems the statement did not go far enough back. [We did see this behavior](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%7C%3D%5C%22Empty%20stream%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221655219047579%22,%22to%22:%221655601297786%22%7D%7D) with the maker once before #2200 merged, the relevant CFD was `83bd8ef8-86be-4773-98d0-3d72404e488e`.

**Comment by da-kami** [comment]
@luckysori @klochowicz I think we agree that the problem of `Empty stream instead of Msg...` during a rollover is a problem. I opened a separate ticket for it: https://github.com/itchysats/itchysats/issues/2263

This problem becomes severe when we fail to read `Msg3`. Other problems related to failing because a stream is empty/terminated can be investigated, but are not severe because they can be retried on a state that is agreed upon.

After your analysis and looking at the logs from a different angle I agree that it is not proven that this is because of one party closing the stream while the other party is still reading. We don't only see this happening for `Msg3`. I will investigate the cases where we see it happening for `Msg0` and `Msg2` to try to understand the cause.
