### ISSUE TITLE
`Failed to get announcement` happens too often

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2264]
We see `Failed to get announcement` errors quite frequently in the logs. This should however only be an error of we fail to fetch announcements repeatedly. If this happens once for an announcement we should log on `debug`.

Ideas for solution:

There are different ways to achieve this. I think the cleanest way would be to let the `oracle` actor track failures for specific announcements. If we fail to fetch the same announcement x times then we report the error.

**Comment by bonomat** [comment]
Counter proposal: 

We are currently fetching announcements for `SETTLEMENT_INTERVAL` ahead of time. Due to small discrepancies, it may happen that a rollover is triggered just before we are fetching the announcement. 

Which means, we could extend the lookahead interval to fetch more announcements from the oracle so that we ensure that we have the one we need.

Creation of the oracle Actor: 

https://github.com/itchysats/itchysats/blob/d6812f5ef1019542beb26068d54350d36b467405/maker/src/main.rs#L133

Lookahead logic:

https://github.com/itchysats/itchysats/blob/970df4ab671c03c9095f56782cc70ca7a1d818c1/daemon/src/oracle.rs#L157
