### ISSUE TITLE
Save the `protocol` version in the rollover data

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2279]
For rollover it can be essential to know with what protocol version the rollover was done so breaking changes do not affect already existing open cfds (i.e. open cfds that were opened prior to the breaking change).

In order to achieve this we will have to save the protocol version with the rollover data and open the rollover substream according to the version.

**Comment by klochowicz** [comment]
Note that this would require us to run either multiple rollover actors on the taker side in order to support this.

**Comment by bonomat** [comment]
I'm not sure I understand why this is needed: 

- for the taker it shouldn't matter, he always only has 1 possible rollover protocol to chose from. Which means, if we make a breaking change to the protocol we need to provide an upgrade path for the taker or accept his position will be force closed.
- the maker on the other hand will have potentially 2+ rollover protocols. Since the taker is requesting the rollover, the maker _knows_ which rollover protocol he is expecting i.e. it is the libp2p-rollover-protocol version. Unless we break changes on the db layer, I don't think the maker needs additional information.

**Comment by da-kami** [comment]
This concerns scenarios where you *upgrade* a taker. We might have scenarios where a taker also has two versions, to ensure compatibility for open positions.

**Comment by bonomat** [comment]
Do you have a scenario in mind where it would make sense to deal with 2 rollover protocols on the taker side? 

If we really can't migrate a rollover protocol version from one to the other (i.e. have to run 2 on the taker side) I would accept force closing the position. I think the maintenance hell out of this would cost us too much. 

We can revisit this if we ever need it but for now I don't see the need. 

Closing this for now. Feel free to re-open if you have more input @da-kami :)
