### ISSUE TITLE
Maker should reject rollover if fails upon starting it instead of just appending `RolloverFailed`

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2294]
When working on https://github.com/itchysats/itchysats/pull/2272 we noticed that upon handling a rollover proposal the `maker` might fail at `start_rollover_maker`. This currently leads to appending a `RolloverFailed` event which is a bit odd. 

At that point the maker should rather append `RolloverRejected` (potentially with a reason) and then spin off a task to send `RolloverRejected` to the other party.
We did not do that back when we implemented it to avoid side effects with the tasks (i.e. only one task per cfd in the rollover actor), but I don't think it is likely that we will run into conflicts there. The problem that we wanted to avoid is the one where we replace a currently ongoing rollover task with another task that would send the rejection (this could happen if a user triggers another rollover while the first one is still ongoing). If we still see this as problem we could introduce a `Spawner` for the rejections so we don't have to replace the task.

**Comment by klochowicz** [comment]
I believe this is related to #2259 . Probably the best way to move forward would be agree about such a thing in an ADR, as it's not just rollover exhibiting such behaviour. IMHO it would be still useful to see whether this was a "manual" vs "automatic" rejection; the first one being the other party actually decided not to proceed with it, and the latter was just a failure due to sending wrong data.

**Comment by bonomat** [comment]
This project is unmaintained
