### ISSUE TITLE
CI failure because rollover stops after the taker receives the accept message

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2319]
Only *some* rollover tests fail not all, so it is not easy to pinpoint what could be the problem.
Also, this problem happens together with other failures, see https://github.com/itchysats/itchysats/issues/2315

CI runs where we see this behaviour:

https://github.com/itchysats/itchysats/runs/7103486103?check\_suite\_focus=true
https://github.com/itchysats/itchysats/runs/7104276002?check_suite_focus=true
https://github.com/itchysats/itchysats/runs/7104941314?check_suite_focus=true

**Comment by klochowicz** [comment]
interesting. from looking at the logs, it seems that one of the parties got stuck in some message handler? Coming back to our earlier discussion today, this is one of the instances where new tracing instrumentation would really help. 

I'll see whether I can add more logs into the CI to dive deeper into this.

**Comment by klochowicz** [comment]
@da-kami I have just noticed that all the timeouts are happening on macos-test job - do you think the virtualenv might have slowed down there for some reason, and 60s is not enough to pass? 
I have encountered some runs, where it failed just narrowly (the protocol actually finished, but not soon enough to cancel the timeout):
https://github.com/itchysats/itchysats/runs/7110385770?check_suite_focus=true

The above hints that there might be some performance regression (either itchysats or macos virtualenv), rather than an issue in the underlying rollover itself.

I will try to see whether we using macos12 will fix this: #2326 
(if it won't, I plan slightly increase the timeout in the tests to see whether this will help - CI failures are really frustrating :/)

**Comment by klochowicz** [comment]
@da-kami all the failing PRs started passing after I merged #2326 . There has been no CI failures despite around 5 retries. I will close it for now, and keep closely monitoring the CI, whether it happens again or not.

It seems that there is a bit of a performance regression - hard to quantify by how much we slowed down the rollovers, but without a doubt we've been failing to complete it within the 60s threshold specified in the tests. I'm not sure whether we should open a ticket for this?

**Comment by bonomat** [comment]
Just one additional note: I can reproduce this locally on macOS 12.4 sometimes. 
My assumption is that it has something todo with https://github.com/itchysats/itchysats/issues/2322

**Comment by klochowicz** [comment]
> Just one additional note: I can reproduce this locally on macOS 12.4 sometimes.
> My assumption is that it has something todo with #2322

Can't tell for sure whether this performance regression is caused by #2322; the performance regression is there for sure, but without benchmarks it's hard to tell by how much we regressed and how much of a problem it is for us in grand scheme of things (it might just happen to cross the arbitrary 60s threshold in the tests). 
We can create a dedicated issue to profile it with flamegraphs if fixing #2322 won't fix it.

**Comment by klochowicz** [comment]
Reopening, as it started happening more again. the workaround with `macos-12` github action wasn't enough :(
