### ISSUE TITLE
Failure to send offers to certain takers

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2322]
We have seen this previously; it happened again, hence I'm creating the issue.

logs on the maker side:
`{"timestamp":"2022-06-29T09:05:21.20733614Z","level":"DEBUG","fields":{"message":"Outbound ping protocol failed: Bad connection: connection is closed","peer":"12D3KooWQKVeZWeD5WBKEjN4pDVjmd4VwyNrdm2Ey6bJWGW7FEw7"},"target":"xtra_libp2p_ping::ping"}`

`{"timestamp":"2022-06-29T08:55:25.79746072Z","level":"DEBUG","fields":{"message":"Failed to send offers: Bad connection: connection is closed","peer":"12D3KooWQKVeZWeD5WBKEjN4pDVjmd4VwyNrdm2Ey6bJWGW7FEw7"},"target":"xtra_libp2p_offer::maker"}
`

"Bad connection" error bubbles up from yamux, which says that the connection is closed.

Restarting the taker did not solve the issue, the taker still couldn't see the offers.

**Comment by da-kami** [comment]
I am encountering this problem at the moment:

![image](https://user-images.githubusercontent.com/5557790/176420311-b16411f1-da74-4d5c-aecb-db601b8454fe.png)

Behaviour: 

The taker sees an offer from the maker, upon trying to take it we run into 

https://github.com/itchysats/itchysats/blob/be6d2645945c3a26f8b1ec6dffe86c415a6184b4/daemon/src/taker_cfd.rs#L204-L206

which flags the offer as outdated, so the taker removes it.
The taker then receives another offer, but it has the same problem. 

I compare the offers being created with what arrives at the taker UI and it does not match, but I wonder what the taker receives then. The price I see is from like ~25 minutes ago.

---

Guesses by me:

Could it be that we are somehow several offers behind because messages piled up...?

**I can confirm that I see the offers that were created about 25 minutes ago dripping in bit by bit. I can predict the offers I will see in the taker by looking at the old logs of the automation, meaning that somehow we only send these offers out now when they should have been sent out quite a while ago!**

**Comment by da-kami** [comment]
Conclusion: Even after restarting the maker we fall back with offers almost immediately, i.e. the offers being produced are not the ones being sent out. This is only on the new offers protocol, the old one sends up to date ones out.

**Comment by klochowicz** [comment]
after trying to debug with tracing instrumentation, we can clearly see that Endpoint actor is badly congested; below is a sample run:

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/8319440/176550325-5dd53514-0552-4481-941d-e2ede8ef403d.png">

it's insanely long to wait in queue for over 8 minutes! and it's really weird that opening a substream takes exactly 20s.... (is this the timeout?). I'll dig deeper into it tomorrow.

**Comment by klochowicz** [comment]
and actual handler (last 20s):
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/8319440/176551858-d18c4858-3774-4d3a-aa43-ed01b3151160.png">

Note that it's all the protocols being there on the queue, not just offers (but they're the most obviously seen)

**Comment by Restioson** [comment]
It seems that a message takes 5 seconds to be sent, but the timeout is 20 seconds, which leads to a buildup. The next question, then, is why it times out in the first place

**Comment by klochowicz** [comment]
this might be related: https://github.com/itchysats/itchysats/issues/2452

**Comment by klochowicz** [comment]
Closing as 0.5 does not experience such severe issues.
