### ISSUE TITLE
Make daemon contract symbol aware from maker-to-taker

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2458]
Right now we assume that every CFD is a BTCUSD position. In order to support different contract symbols the first step is to make the daemon aware of the symbol i.e. make sure that both sides know which symbol a CFD is for. 

aka: Send BTC/USD symbol all the way through from Maker to Taker.

**Comment by klochowicz** [comment]
TradingPair was already stored in the Offer - unfortunately it was hardcoded there and in the projection though. 
I have created #2576 to make sure it goes all the way from the taker to the UI :)

this should be enough, although we should upgrade offer protocol before we send EthUsd to the takers (otherwise the hard-coded `BtcUsd` on the taker side will make them think it's a really good deal to buy BTC :P)
