### ISSUE TITLE
CI test run times can be really long

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2473]
We had a CI `macos` test run that took `15` minutes to complete! 
I don't think it is expected that CI takes *that* long.

See: https://github.com/itchysats/itchysats/runs/7407394638?check_suite_focus=true on https://github.com/itchysats/itchysats/pull/2469

**Comment by klochowicz** [comment]
it is really long? I'm not sure it's worth reporting - we all know that unless we run actor tests in debug they will take long due to the contract setup taking a lot of time in all cases. There was an idea to store an opened Cfd in DB so that we can start almost all tests from "open" state, but we never actioned that due to other priorities.
If we care about the CI test time, we might to give this idea a spin :)

Also: I see that in the linked run macOS run took 17m, whilst ubuntu took 16m - is that additional minute worth singling out macos?

**Comment by bonomat** [comment]
You are both right, _all tests_ are now significantly slower. 

This run here was relatively fast: https://github.com/itchysats/itchysats/actions/runs/2688891218
- ubuntu: 9m
- macos: 7m

and the one afterwards was slow: https://github.com/itchysats/itchysats/actions/runs/2689104767
- ubuntu: 16m
- macos: 21m

ever since the tests run for >15m

It looks like ever since this landed we slowed down: https://github.com/itchysats/itchysats/pull/2404


![Actions-·-itchysats-itchysats](https://user-images.githubusercontent.com/224613/179864300-a1ee6fb7-8354-499e-9e6a-09ca70adf8d6.png)

**Comment by bonomat** [comment]
cc @Restioson

**Comment by Restioson** [comment]
I'll try disable some more stuff from the macro's generated code itself when the tracing env var is disabled. It could be the 1s sleep or flush that's taking long.
