### ISSUE TITLE
What happens if `RolloverCompleted` cannot be overwritten?

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2662]
Now that we segregate the storage of the DLC data from the `RolloverCompleted` event, we can run into a situation where we succeed in appending to the `events` table, but fail to overwrite the DLC data stored in the `rollover_completed_event_data` table.

https://github.com/itchysats/itchysats/blob/1305340f1fbb8567ed72f594bbf03013cbae93da/sqlite-db/src/lib.rs#L227-L290

Is this a problem?

**Comment by da-kami** [comment]
Yes, I think this can be a problem, because it can lead to cases where we *succeed* to save the event, but we *fail* to insert the data related to the event.
For this particular case, I think this should be handled in one complete transaction, i.e. we should append the event *and* overwrite the data in one database transaction. As far as I could see in `append_event` this can actually be easily achieved by not passing down the `connection`, but a `transaction` that is committed in `append_event`.

Note that this might still have unwanted side effects, but it would definitely be more correct for this particular case!

On top of that: Saving in the database *should* not fail, if it does we should retry to save! 

---

Note:
This is to some extent part of the discussion related to handling `event`s in general.  
At the moment we *always* (try to) save the event first and then we *process* the event. But, if processing the event fails the event is not removed (because it did happen after all) and we *assume* that processing it will be (eventually) retried. Given that retry is not implemented in many cases, this can lead to scenarios where the system *thinks* that something happened, but it did not actually have an effect. I describe this problem for transaction handling in #2465 - in case of rollover data it is slightly different because it concerns our database rather than the blockchain related state,  but the overall problem is related to events being saved without considering that processing the event may fail.

**Comment by luckysori** [comment]
> For this particular case, I think this should be handled in one complete transaction

I think we are in agreement. Let's do this.

> Note that this might still have unwanted side effects, but it would definitely be more correct for this particular case!

Can you elaborate? I can't think of anything.

> On top of that: Saving in the database should not fail, if it does we should retry to save!

At the moment we don't do this, right? We just wait for the application to try to emit the same event later.
