### ISSUE TITLE
Remove contract symbol from feed api

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2673]
Currently the feed api exposes individual endpoints per contract symbols by which offers and quotes can be put into context. However all other data events are replicated like wallet, maker_status, maker_identity and cfds.

Following the original design of the feed api the more sensible approach would have been to keep one endpoint which provides all feeds and make the offers and quote feeds contract symbol aware to allow the subscriber to deal with it accordingly.

https://github.com/itchysats/itchysats/blob/64f07eb160c428999258bdb7c66a4cade682c6b0/daemon/src/projection.rs#L90-L98

At a later stage we could even think about adding a query parameter to the feed to allow for filtering specific event types. e.g. only send quotes for ethusd, etc. I think that would give us far more flexibility as such a filter could also implement something like versioning into the query language. In my opinon this kind of design will also help us eventually If we intent toopen up the daemon api for third party applications - as integration will be simplified.

**Comment by bonomat** [comment]
Make sure we are able to only subscribe to the sse topic (not sure if the term is correct ) we are _currently_ interested in: I.e. if we want to trade BTCUSD we should not subscribe to ETHUSD as this would make our UI re-render everything on any update to either BTCUSD or ETHUSD. 
Also, make sure that it is possible to get _old_ offer data as otherwise switching between contract symbols won't show any information until a new offer was received. 

Differently said: I tried to only subscribe to the contract symbols We are interested in but that will make us miss offers. If we subscribe to all topics at the same time we will re-render the whole page every time a new offer of either topic was received. 

I failed at this hence the introduction of the url parameter. But maybe I was just doing it wrong :) 

I hope this saves you some time if you decide to go down this path. :)

**Comment by bonomat** [comment]
> Make sure we are able to only subscribe to the sse topic (not sure if the term is correct ) we are currently interested in: I.e. if we want to trade BTCUSD we should not subscribe to ETHUSD as this would make our UI re-render everything on any update to either BTCUSD or ETHUSD.
> Also, make sure that it is possible to get old offer data as otherwise switching between contract symbols won't show any information until a new offer was received.
> 
> Differently said: I tried to only subscribe to the contract symbols We are interested in but that will make us miss offers. If we subscribe to all topics at the same time we will re-render the whole page every time a new offer of either topic was received.
> 
> I failed at this hence the introduction of the url parameter. But maybe I was just doing it wrong :)
> 
> I hope this saves you some time if you decide to go down this path. :)

Moving this to the PR, sorry for posting here ...
