### ISSUE TITLE
Should we be sending all CFDs through the projection feed on every update?

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2709]
I suppose this was done on purpose to keep the client simpler, but does this have an impact on performance?

The same observation applies to our offer and quote feeds.

**Comment by da-kami** [comment]
The simple answer: No

I would propose a pattern, where we don't send data over the update feed, but only tell the UI that something changed, and the UI can then decide what data is to be loaded.
I think this will result in a more efficient user interface and experience, because the UI (i.e. the consumer) decides what is needed according to what is displayed. This allows adding e.g. pagination in a simple way.
However, it will require somewhat more code, because we will have to add endpoints to fetch data.

For offer and quote I would apply the same principle, but it is not as critical because there is no ever growing list of quotes/offers.

**Comment by luckysori** [comment]
@da-kami: Could you open a ticket to reflect your proposal? We may not want to tackle this any time soon, but it would be good to document this good idea.
