### ISSUE TITLE
What does this span do and why do we need it in the `model::Cfd` code?

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2727]
https://github.com/itchysats/itchysats/blob/e4f910f35070c47672c8e37e224b51e3b532e833/model/src/cfd.rs#L840-L841

I would like to understand why we decided to place this span in the model. I would have expected this to be part of the protocol. 

As far as I could see this is the only `tracing::span!` in the model, so I am wondering if this is even intentional?

**Comment by Restioson** [comment]
I also saw this, seems like it was introduced by @luckysori at some stage. I thought maybe it could be to add the order id to the logs?

**Comment by luckysori** [comment]
It was intentional. As @Restioson pointed out, the idea was to add the order ID context to logs emitted inside of `Dlc::base_dlc_params`. Here's an [example of how it looks on Grafana](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22%7D%20%7C%3D%20%60Building%20base%20DLC%20params%20for%20rollover%20from%20previous%20commit%20TX%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221660131956285%22,%22to%22:%221660235362723%22%7D%7D).

**Comment by luckysori** [comment]
I thought it was important because otherwise if you filter the logs by order ID you might miss the important detail that a particular rollover was a "retry" rollover.

**Comment by luckysori** [comment]
@da-kami: Are you satisfied with this explanation? Please reopen if not.
