### ISSUE TITLE
Switching between contracts in taker UI has no effect

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2729]
I think the PR: #2679 broke the dropdown in the taker UI. 

Switching between contract symbols will not update the rate. I believe this is because we do not receive the necessary event and do not reconnect to the stream to retrieve old offers. 

The taker UI will only update if a new offer was received. 

I tried to explain this in this comment: https://github.com/itchysats/itchysats/issues/2673#issuecomment-1212732598

Available offers: 

<img width="747" alt="image" src="https://user-images.githubusercontent.com/224613/185883680-bd75220b-663e-4868-8a93-35a0c5ee6a77.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/224613/185883768-df436caa-0697-4cb1-bcc7-7585a2858b09.png">

<img width="961" alt="image" src="https://user-images.githubusercontent.com/224613/185883807-ec54e30c-db84-45f3-a267-648157e81cee.png">

**Comment by bonomat** [comment]
Note: this was the reason why I introduced the path parameter in the first place. 

I propose timeboxing the bug investigation to 1h and rather rollback the PR if it has worked before.

**Comment by bonomat** [comment]
I've verified it. Pre this PR it was working.

**Comment by holzeis** [comment]
@bonomat I don't think this is a ui-bug, but an issue with how we get the latest events from the daemon. With #2679 we combined ETHUSD and BTCUSD offers into a single event. Now if we request the latest event we either get ETHUSD or BTCUSD. This happens because we using the channel as state to republish the latest sent event. The reason why it works with different API endpoints is because we keep separate channels for ETHUSD and BTCUSD.

However, I don't think that's the best design, because it makes our API very inflexible and introduces an additional connection. Instead I propose that we separate the state from the channel and manage it independently - thus allowing us to be more flexible on what we sent upon a subscription request.

**Comment by bonomat** [comment]
@holzeis : to paraphrase what you are saying: 
we should not get the latest state when connecting to the `feed` but have an extra API which allows us to get the latest state explicitly (e.g. the latest offer for a particular contract) and when connecting to the `feed` we will only get _new_ events. 

I think this is a fair alternative to our current approach. I have seen something similar to what we are using in [the wild](https://www.bitmex.com/app/wsAPI) though. For certain events BitMEX sends out a full image of the current state when connecting to the websocket and then only sends out diffs whenever something changes. 

I personally prefer what you are proposing because this makes things more explicit.

**Comment by holzeis** [comment]
@bonomat well we could split it into different APIs, but personally I like that on subscription I get the latest state, respectively this could also be an argument on the API call if I want to get the latest state or only new events. I would vote for keeping the whole feed api bundled into one endpoint and manage filtering (behaviour) through e.g. query parameters. That way the client can decide what he is interested in - how many feeds he would like to use, etc. 

I guess that flexible design would also be helpful on the long run, when we considering that solutions will be built around itchysats. (Also note, that we already have different clients with different needs for the feed api - see auto taker / maker)
