### ISSUE TITLE
ETHUSD: Long and short liquidation price are swapped

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2760]
In addition to https://github.com/itchysats/itchysats/issues/2754 we should check how we compute the liquidation prices. Right now they are swapped: 

Long position shows short liquidation price and vice versa: 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/224613/187026281-5a5f48b9-4b6b-4ff9-b39d-e5108a21ca3f.png">

<img width="580" alt="image" src="https://user-images.githubusercontent.com/224613/187026289-a6eb8129-01b4-46e2-9803-98e476857792.png">

**Comment by da-kami** [comment]
https://github.com/itchysats/itchysats/issues/2774 should be resolved with https://github.com/itchysats/itchysats/pull/2790 
The flipped liquidation price is yet to be investigated, hence I am reopening this ticket!

**Comment by da-kami** [comment]
Note: Further assertions in the actor tests - https://github.com/itchysats/itchysats/pull/2799 - currently point to this problem coming from the UI.
Once https://github.com/itchysats/itchysats/pull/2799 is finished (see https://github.com/itchysats/itchysats/issues/2802) I will have another look at this.

**Comment by bonomat** [comment]
So, the problem is again pointing us to fix #2786

The issue is that we create an offer from the perspective with liquidation price of the maker.
In the frontend, we think we just flip it around but this is wrong because the liquidation price for the maker != the liquidation price for the taker.

In values expressed (other values omitted): 

These are the offers as received in the frontend: 

```
[
  {
    "contract_symbol": "EthUsd",
    "position": {
      "key": "Long"
    },
    "price": "9850.00",
    "leverage_details": [
      {
        "leverage": 2,
        "liquidation_price": "4925",
      },
      {
        "leverage": 1,
        "liquidation_price": "1",
      },
      {
        "leverage": 3,
        "liquidation_price": "6567",
      }
    ],
  },
  {
    "contract_symbol": "EthUsd",
    "position": {
      "key": "Short"
    },
    "price": "11165.00",
    "leverage_details": [
      {
        "leverage": 2,
        "liquidation_price": "16747",
      },
      {
        "leverage": 1,
        "liquidation_price": "22330",
      },
      {
        "leverage": 3,
        "liquidation_price": "14886",
      }
    ],
  }]
```

It says: 
- maker long: 
 - price: `9850`
 - liquidation price `4925`, ..
- maker short:
 - price: `11165`
 - liquidation price `16747`, ...

From the maker perspective this is correct.
Now if we want to turn this around, we will need to flip the liquidation prices.

Note: one problem is that we need to have both offers available which we can't be guaranteed because they come through 2 different event sources. Again, pointing to https://github.com/itchysats/itchysats/issues/2786 ;)

**Comment by bonomat** [comment]
Note: one problem is that we need to have both offers available which we can't be guaranteed because they come through 2 different event sources. Again, pointing to https://github.com/itchysats/itchysats/issues/2786 ;)

**Comment by bonomat** [comment]
An alternative solution would be to compute the liquidation price in the frontend then we would not need to swap things around.

**Comment by da-kami** [comment]
Concerning the specific problem: 

To my knowledge in `0.5.5` the liquidation price is still displayed correctly in the taker UI and not flipped.
The liquidation price sent out in `LeverageDetails` is supposed to be according to the *own* position and leverage, see:

https://github.com/itchysats/itchysats/blob/59a7b9b8f455f767845ef0c2162a8a3b0efd2b98/daemon/src/projection.rs#L1347-L1350

However, I checked the code and we are still using the `own_position` to calculate, so I am a bit confused now 😅

I think you are correct that the flip in the taker UI causes this problem - How did this ever work in previous versions?
Did we flip the liquidation price again? 😅

---

Concerning making the model better:

I totally agree that the projection model is not designed well and should be cleaned up. This concerns both the `projection::CfdOffer` and `projection::Cfd`.

We have argued in the past, that the projection should always model what the consumer needs, i.e. the taker UI should receive the values from the taker's perspective; the maker UI / other consumers might need even more fields because they may require taker and maker specific values, we had that problem in the past that suddenly we only say maker related data and that was not sufficient.

In the past we have discussed to split the model between maker and taker, so that the API can cater for the needs of the consumers better. I think this would be a good way forward, but will require some more work.

Note: We can change the internal model (i.e. `model::Cfd`, `model::Offer`) as well, but they are independent of changing the API (i.e. the projection).

**Comment by da-kami** [comment]
@bonomat I think what you proposed in https://github.com/itchysats/itchysats/pull/2764 - i.e. remove the flip from the UI - would be a good step forward, but we would then have to start refactoring the `projection::CfdOffer` model. 
For now we could opt to just adapt it so it works for the taker-UI and ignore the maker-UI 😬
To my knowledge there are no other consumers of the `projection::CfdOffer` at the moment.

**Comment by bonomat** [comment]
>  The liquidation price sent out in LeverageDetails is supposed to be according to the own position and leverage, see:

well that is blody confusing 😅
