### ISSUE TITLE
Do not send offers via wrong `offer` protocol to peers

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2763]
Since https://github.com/itchysats/itchysats/pull/2680 we are sending offers via two different protocols to _all_ takers. One of those protocols will always fail during the negotiation phase. I documented this behaviour here: e4f910f35070c47672c8e37e224b51e3b532e833.

As noted in that commit message, on the maker side we can suppress these warnings because we can choose to ignore that specific error when opening the substream. On the taker side it is emitted in a place where we handle all possible incoming substreams, so it's unavoidable.

To not send needless offers to takers we need to evolve the `Endpoint` to be able to decide during runtime what protocol to dial to which takers, depending on their supported listen protocols.

---

If you look at the [Grafana logs](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22%7D%20%7C%3D%20%60negotiation%20failed%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221660809217202%22,%22to%22:%221661734356186%22%7D%7D) you can see that the frequency for this particular log message increased just after https://github.com/itchysats/itchysats/pull/2680 merged.

**Comment by bonomat** [comment]
Adding it to this iteration. But if it's not critical, feel free to postpone.

**Comment by luckysori** [comment]
Since https://github.com/itchysats/itchysats/pull/2680 we are sending offers via two different protocols to _all_ takers. One of those protocols will always fail during the negotiation phase. I documented this behaviour here: e4f910f35070c47672c8e37e224b51e3b532e833.

As noted in that commit message, on the maker side we can suppress these warnings because we can choose to ignore that specific error when opening the substream. On the taker side it is emitted in a place where we handle all possible incoming substreams, so it's unavoidable.

To not send needless offers to takers we need to evolve the `Endpoint` to be able to decide during runtime what protocol to dial to which takers, depending on their supported listen protocols.

---

If you look at the [Grafana logs](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22%7D%20%7C%3D%20%60negotiation%20failed%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221660809217202%22,%22to%22:%221661734356186%22%7D%7D) you can see that the frequency for this particular log message increased just after https://github.com/itchysats/itchysats/pull/2680 merged.

**Comment by luckysori** [comment]
I'm removing the `bug` label given what I mentioned in my previous comment. I'll assign myself to this ticket and repurpose it to describe the current behaviour and how I think we should solve it.

**Comment by luckysori** [comment]
I'll assign myself to this ticket and repurpose it to describe the current behaviour and how I think we should solve it.
