### ISSUE TITLE
Better restrict `Contracts` values to what is allowed

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2898]
This is a ticket that resulted out of a usage interview with @holzeis 

Currently it is only possible to trade in increments of `100` using values between `100` and `1000`. 
However, we use an editable text field to define how mange `Contracts` on can buy. This is not intuitive. We can make this better by restricting the choices further (i.e. the text field should not be editable) and explaining why this is restricted like this.

**Comment by klochowicz** [comment]
we also need to remember that different constraints apply per different `ContractSymbol`:
increments are the `LotSize`, and min/max of the offer are the range. 

I would strongly oppose making the field not editable, I'd rather give better explanation if someone types invalid value.

**Comment by bonomat** [comment]
I think this is standard internet behavior? 😅 

What we could do is: 
- move the error warning where it belongs
- auto round the input value to 100 (or different lot size) when the focus is dropped.

Screenshot from BitMEX. 

<img width="449" alt="image" src="https://user-images.githubusercontent.com/224613/188764513-96359ba7-b4e4-471e-b7be-b5498f255479.png">

**Comment by da-kami** [comment]
@holzeis any opinion on this? 
Not sure this is important enough to action anytime soon 😅

**Comment by holzeis** [comment]
Ok first of all, I don't think we should align too much on the bitmex user interface. Judging from the screenshot they also do not have the best UI/UX skills in their team 😅. e.g. they use the same color coding for signaling danger (warning) on the leverage slider, error messages and sell / short button. That makes me nervous 🙈.

Regarding restricting the contract inputs. If we know what the input can be, why do we let the user enter something else. I think that frustrated me the first time I used the user interface. I was like why can't I choose 105 contracts. Why do I have to go for an increment of 100. An error message telling me that it has to be an increment of 100 is not very helpful. How about a slider instead of a number input field?

**Comment by klochowicz** [comment]
> Ok first of all, I don't think we should align too much on the bitmex user interface. Judging from the screenshot they also do not have the best UI/UX skills in their team 😅. e.g. they use the same color coding for signaling danger (warning) on the leverage slider, error messages and sell / short button. That makes me nervous 🙈.
> 
agree. there's not much benefit for us to follow bitmex ui patterns. coming from mission critical systems, I have `red=danger` association deeply ingrained in me, and I rarely click short button because of that (and partly because it's hidden behind a tab that does not look like a tab...). Please comment on the discussion that I linked earlier or just come up with different colour :p 
Totally agree on not trying to follow them and their UI/UX being not great.

> Regarding restricting the contract inputs. If we know what the input can be, why do we let the user enter something else. I think that frustrated me the first time I used the user interface. I was like why can't I choose 105 contracts. Why do I have to go for an increment of 100. An error message telling me that it has to be an increment of 100 is not very helpful. How about a slider instead of a number input field?

We should expose lot size clearly, and have info for that that this is the increment value. Slider for number input field is another anti-pattern that should be avoided; imagine trying to precisely type how many you want with a slider ;/
The error perhaps could be a bit more helpful, saying that these are the terms of the offer due to the lot size constraint defined *by the maker*, and as a taker one has to live with that.

**Comment by bonomat** [comment]
This project is unmaintained
