### ISSUE TITLE
Store auth sessions

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2978]
Currently the daemon does not store sessions but keeps them in memory.

1. Electron users will have to login every time they stop and start the app. Since electron will also always stop and start the daemon - the user experience is different to the regular umbrel user, as closing the browser will not stop the daemon.
2. Scaling the daemon will require sticky sessions.

**Comment by bonomat** [comment]
The downside of storing it in the database is that loading from the db is more costly than from memory (without any caching implemented). I thought about it shortly when implementing and thought that users do not restart their service and hence it's not an issue. 

Re electron: imho the electron app should keep running in the backround as well. Otherwise you might miss rollovers and your positions will get closed. 

Additionally, I think it's fine to ask for a password when you restart the app. Could be a security issue if you start it again and don't have to login anymore.

**Comment by klochowicz** [comment]
> Re electron: imho the electron app should keep running in the backround as well. Otherwise you might miss rollovers and your positions will get closed.

By default the electron app keeps running after you click "X" on the window (it just hides in the background).

> Additionally, I think it's fine to ask for a password when you restart the app. Could be a security issue if you start it again and don't have to login anymore.

I agree with this.

**Comment by holzeis** [comment]
Alright, you convinced me in regards to the electron app. However, I still think there are downsides in scaling with keeping the session state in memory. (which is not really necessary in my opinion - e.g. we could do the same thing stateless using json web tokens)

**Comment by bonomat** [comment]
What do you mean with scaling?

**Comment by holzeis** [comment]
horizontally scaling the taker daemon, bit I guess that's not a focus now.

**Comment by bonomat** [comment]
Not really. For that we have other issues to fix: concurrent wallet access for example.

I'll close this ticket as it looks like we are aligned that we don't want it for now.
