### ISSUE TITLE
Service to notify users of ItchySats network connectivity issues

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#3049]
This touches on #2888  but goes further.

It can happen that itchysats runs into connectivity issues such as:

```
2022-09-28 19:00:19 DEBUG fallible task handle_error{err=}:send_async_next:xtra_actor_request{actor_type=xtra_libp2p::endpoint::Endpoint message_type=xtra_libp2p::endpoint::FailedToConnect}:xtra_message_handler:Handle FailedToConnect: xtra_libp2p::endpoint: Failed to connect: : : select error: Protocol error: I/O error: Network is unreachable (os error 101): Protocol error: I/O error: Network is unreachable (os error 101): I/O error: Network is unreachable (os error 101): Network is unreachable (os error 101)
```

It's hard for a user to notice this because the only visible problem in the UI is not being connected to the maker and some parts "loading". It's not obvious there is a connectivity issue.

It would be great to provide more feedback to the user.

We can notifications for cases where the user has the interface open (see #2888), or the node is still able to e.g. send emails out:

- Push notifications in the UI so that a user gets warned in case the UI is open.
- Email notification in case the node is still able to send out emails.

But, if the Umbrel node is actually down it would still be great to get notified if itchysats is unable to connect to the network.
For this case it would be especially important for the use to know, because they will likely have to fix a problem.

We could build a service that offers:

1. Users can voluntarily sign up for the service and register an email (as well as their itchysats)
2. The users node then sends heartbeats to the service (or the service tries to ping the user's itchysats)
3. If the services notices that the user's itchysats is not reachable the service could send out an email to the user

Potentially this service *cold* be built into the maker (because the maker knows with which taker a position is open), but we could also try to build this as a separate service.

**Comment by klochowicz** [comment]
IMHO instead of building a niche product, we could stress the benefits of monitoring for uptime yourself in a blog post and educate users how to do it themselves.


# Grafana

-   you can use a free instance of grafana cloud to monitor your umbrel: <https://grafana.com/blog/2022/05/25/how-to-monitor-an-umbrel-server-running-a-bitcoin-node-with-grafana-cloud/>
-   note: we could create a guide how to pimp it up with ItchySats metrics! (after all, they're available)

# RasPi nodes - monitor for uptime of the onion address  

-   source: <https://tech.michaelaltfield.net/2021/03/12/monitoring-tor-onion-websites-uptime-alerts/>
-   use \`curl\` or \`mon\` on your linux node and just monitor umbrel node locally (if the issue is just the node)
-   tor2web proxy + IaaS provider (uptimerobot etc)

# uptime kuma - available on the umbrel store 

-   source: <https://bitcoinmagazine.com/technical/how-to-monitor-uptime-home-bitcoin-mining>
-   a self-hosted notification service, that can for example ping you on Telegram
-   con: not good if node goes down, but can detect misbehaviour / notifications in ItchySats

as for the push notifications (which would be a great improvement): they could also be accessible with basicauth for grafana/uptime kuma so that the user could get alerts delivered if they wish.

**Comment by bonomat** [comment]
This project is unmaintained
