### ISSUE TITLE
Utilise SSE heartbeat to detect loss of connection to the backend

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#482]
As @da-kami pointed out, we can use SSE event heartbeat to detect the loss of the event source.

This would get rid of the keepalive requests from the frontend.

**Comment by klochowicz** [comment]
Tentative design:

https://github.com/comit-network/hermes/pull/476#pullrequestreview-798423194

note: we might be able to leverage the SSE heartbeat instead of creating our custom event.

**Comment by da-kami** [comment]
I think this ticket is quite important for getting a better UX:

Since using the UI within the Umbrel setup I had it several times that I kept a tab open but when I came back the information was outdated.
I think that most errors where we see an "outdated user interface" are related to this problem. These are problems that I usually fix by "refreshing the page" - but it is often hard to spot that values are outdated.

A bit more context:

At the moment we monitor the connection to the daemon using the `/alive` endpoint. 
This is not incorrect, but incomplete, because it does not tell us anything about the connection to the feed. There are various scenarios where the feed connection is lost, but the alive endpoint is still reachable. 

I think the heartbeat on the SSE feed should replace the periodic request to `/alive`. 
We should track that we always receive a heartbeat within a certain time window, and if not try to reconnect to the feed.
