### ISSUE TITLE
Taker UI displays `0.0` when there's no order from the maker

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#524]
This is confusing, as it can be assumed that the app broke or the connection to the maker got lost.

also: it's not clear in the first place that the price is the offer price. I actually thought it would be current BTC price.

**Comment by 1010Tom** [comment]
> also: it's not clear in the first place that the price is the offer price. I actually thought it would be current BTC price.

I propose to do exactly that, i.e. show the current price from BTC/USD here (Bitmex offers that as an event source afaik it should be `wss://www.bitmex.com/realtime?subscribe=instrument:.BXBT` ).

**Comment by klochowicz** [comment]
but then we still need to show the offer price somewhere else?

**Comment by 1010Tom** [comment]
I'd do that in the dialog then. I.e. this is a _market order_. You don't 100% know what rate you get before you hit send.

**Comment by 1010Tom** [comment]
@da-kami : will look into why the taker does not pick up the latest price and I will update the price to show the BXBT rate.

**Comment by da-kami** [comment]
One cause of this error is  https://github.com/itchysats/itchysats/issues/526 which I can reproduce locally. 
So far, without going over the actual wire I am unable to reproduce the behavior where we don't receive the order after taking a cfd. 

Some more notes on what was observed so far to get a more complete picture:

When testing over the wire it was observed, that even though there was a connection with the maker (taker and maker were in the middle of exchanging contract setup parameters), the taker did not properly receive the new order that was re-published. 
Re-publishing another order manually did not help. Refreshing the taker did not help. Only restarting the daemon fixed the problem. 
This behavior is weird, because the connection was definitely not dropped (contract setup messages were exchanged). But the order messages somehow did not reach the taker UI.

**Comment by da-kami** [comment]
was able to reproduce locally, checking :)
