### ISSUE TITLE
Version displayed on startup is not correct

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#537]
```
2021-11-11 22:26:32  INFO Running version: 0.1.1
```

I am fairly certain I am running a version that is _newer_ than the 0.1.1 tag (I pulled the `preview` docker tag) but this is not reflected in the version number.

**Comment by thomaseizinger** [comment]
As discussed, our use of the `preview` tag might interact with this badly.

Let's get rid of the `preview` tag and instead publish a new docker container every time we push to master.

FYI: @bonomat @da-kami

**Comment by bonomat** [comment]
If I understand you correctly: you want to get rid of the `preview` tag and release in favor of having just docker images?

**Comment by thomaseizinger** [comment]
> If I understand you correctly: you want to get rid of the `preview` tag and release in favor of having just docker images?

Yes. I am not sure if it solves the above problem but our use of the `preview` tag interacts badly with `vergen` anyway because it will just say `preview` which gives us no indication of which version it is.

**Comment by bonomat** [comment]
my understanding is that it should work though... we are using git `lightweight tags` and `VERGEN_GIT_SEMVER_LIGHTWEIGHT` should use that. 
So the question is, why does vergen not use it? If I use a local tag  and build it, it works.


Anyway, instead of removing the `preview` release, wouldn't it be better to use a different var, e.g. 
`VERGEN_GIT_SEMVER_LIGHTWEIGHT-VERGEN_GIT_SHA_SHORT`

this would print `0.1.1-75-gbe4b8fa-be4b8fa` on the latest master. 
or with a `test` tag: `test-be4b8fa`

**Comment by thomaseizinger** [comment]
> Anyway, instead of removing the `preview` release, wouldn't it be better to use a different var, e.g. `VERGEN_GIT_SEMVER_LIGHTWEIGHT-VERGEN_GIT_SHA_SHORT`
> 
> this would print `0.1.1-75-gbe4b8fa-be4b8fa` on the latest master. or with a `test` tag: `test-be4b8fa`

I am not a fan of taping over problems. Our use of vergen conflicts with the idea of a rolling Git tag. It might not be directly related to this issue _but_ if we fix this issue, it would surface that our use of vergen is useless. Hence I want to do both:

1. Fix this issue so vergen picks up the correct tag
2. Get rid of the `preview` tag because it will conflict with that solution

**Comment by bonomat** [comment]
Are you against using `VERGEN_GIT_SEMVER_LIGHTWEIGHT-VERGEN_GIT_SHA_SHORT`? 

--------

Looking into the issue why we don't pick up the tag: the issue could be how we checkout our repository

```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
```

taken from https://github.com/itchysats/itchysats/runs/4220905293?check_suite_focus=true


As you can see, we do not fetch the tags, so that could be one issue. 

The other one is that we checkout `github.event.release.target_commitish` which should resolve to the branch. 
But what we actually want is checkout the tag, this should be in `GITHUB_REF`.

**Comment by thomaseizinger** [comment]
> Are you against using `VERGEN_GIT_SEMVER_LIGHTWEIGHT-VERGEN_GIT_SHA_SHORT`?

No, I don't mind which vergen strategy we use as long as it uniquely identifies the commit the software has been built of.

Like I said above, it is not directly related but I still want to get rid of the preview tag. We've changed our assumptions from when we introduced that. We are using docker images now which can also be published directly off master so we no longer need to do this hack of having a rolling tag to ship artifacts.

**Comment by bonomat** [comment]
Ah, now I understand you: so you want to get rid of the whole `preview` release workflow: including binaries and tag and just publish docker whenever we merge into master. 

That would simplify things but we lose the binaries.

**Comment by thomaseizinger** [comment]
> That would simplify things but we lose the binaries.

I don't think we need them for every merge to master, do we? Normal releases will have binaries and everyone who wants the new hot stuff can use docker.

**Comment by bonomat** [comment]
I double down on the assumption that we do not pull the tags correctly: 

1. we fetch the repository without tags 
```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
```

```
--no-tags

    By default, tags that point at objects that are downloaded from the remote repository are fetched and stored locally. This option disables this automatic tag following. 
```

I reproduced this locally: 

Fetch first 
```
 git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin
```


Checout master
```
git checkout --progress -B master refs/remotes/origin/master 
```

Show tags
```
git log --no-walk --tags --pretty="%h %d %s" --decorate=full

be4b8fa  (tag: refs/tags/test) Merge #571
dc190cf  (tag: refs/tags/0.1.1) Merge #506
5891ad6  (tag: refs/tags/0.1.0, refs/heads/dont-fail) Merge #398
990b23a  (tag: refs/tags/preview) Merge #291

```
--> as you can see, `preview` is quite outdated

So I force fetch it, `preview` gets updated
```
 git fetch --tag --force

From github.com:itchysats/itchysats
 t [tag update]      preview    -> preview

```

Show log again
```
git log --no-walk --tags --pretty="%h %d %s" --decorate=full

0fc8b24  (grafted, HEAD -> refs/heads/master, tag: refs/tags/preview, refs/remotes/origin/staging, refs/remotes/origin/master, refs/remotes/origin/HEAD) Merge #699
be4b8fa  (tag: refs/tags/test) Merge #571
dc190cf  (tag: refs/tags/0.1.1) Merge #506
5891ad6  (tag: refs/tags/0.1.0, refs/heads/dont-fail) Merge #398
```


That being said, I think the _bug_ here can be fixed by telling the github action to pull tags. 

-------------

In regards to the other point: 
> I don't think we need them for every merge to master, do we? Normal releases will have binaries and everyone who wants the new hot stuff can use docker.

A simple solution would be to remove the logic around creating preview builds and trigger a github action which builds the docker image. For that I would propose to build the taker and maker inside the docker image. 
This might be slower, but would give us reproducable docker images and we can make use of the power of buildx to create multiplatform docker images, e.g. something like: 


(untested)
```
FROM debian:bullseye-slim

LABEL org.opencontainers.image.source https://github.com/itchysats/itchysats

ARG GIT_TAG
ARG FRONTEND
ARG BINARY

RUN git clone -b $GIT_TAG --depth 1 git@github.com:itchysats/itchysats.git /src/
RUN cd $FRONTEND-frontend && yarn && yarn build
RUN cargo build --release --bin $BINARY

VOLUME data

# HTTP Port and P2P Port
EXPOSE 8000 9999

ENTRYPOINT ["/src/release/${BINARY}", "--data-dir=/data", "--http-address=0.0.0.0:8000"]
```

What do you think @thomaseizinger ?

**Comment by thomaseizinger** [comment]
Thanks for getting to the bottom of the tag issue!

Building within the docker image sounds good to me. Just need to make sure we use multi-stage builds to keep the image size small!

If it is not too hard, it would be amazing to use https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md as the base :)

**Comment by thomaseizinger** [comment]
Re-opening this because now we are running into the following:

```
❯ docker run --pull always --rm -v$PWD/data/preview-taker:/data -p8886:8000 ghcr.io/itchysats/itchysats/taker --maker=159.196.154.67:9999 --maker-id=69a42aa90da8b065b9532b62bff940a3ba07dbbb
11d4482c7db83a7e049a9f1e testnet
latest: Pulling from itchysats/itchysats/taker
e8614d09b7be: Already exists
c6f4d1a13b69: Already exists
a1f1879bb7de: Already exists
7c94f3478345: Pull complete
Digest: sha256:2cdfccc2a3b608715d5991fcb7536f405046ef45600af2a234ae17b925cdedce
Status: Downloaded newer image for ghcr.io/itchysats/itchysats/taker:latest
2021-11-29 23:52:43  INFO Initialized logger
2021-11-29 23:52:43  INFO Running version: preview
2021-11-29 23:52:46 DEBUG Taker actor system ready
```

> 2021-11-29 23:52:43  INFO Running version: **preview**
