### ISSUE TITLE
Radio boxes are not selectable

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#539]
The UI uses disabled radio buttons to display the transactions.

![image](https://user-images.githubusercontent.com/5486389/141378415-7cfa295c-2750-4d58-9fc7-937bfced16dc.png)

As a user, I expect to be able to select radio buttons to make a choice, yet there is no indication on when I would be able to select any of these radio buttons.

**Comment by da-kami** [comment]
I think you are referring to "the timeline of transactions" that is not visibly a timeline. I think we have to invest time into making this part better, so it more obviously represents the "timeline of transactions". 

Writing this because I think the fact that this is a radiobutton is somewhat irrelevant, the radio button serves as a placeholder here.

**Comment by bonomat** [comment]
> As a user, I expect to be able to select radio buttons to make a choice, yet there is no indication on when I would be able to select any of these radio buttons.

These are not radio buttons but circles ... UI failure 😅🙈

https://github.com/itchysats/itchysats/blob/41aad18effd99be89fba80dc9996fa523672fd65/taker-frontend/src/components/History.tsx#L236-L244

**Comment by thomaseizinger** [comment]
Lol, I didn't look at the code and assumed we just used radio buttons as place holders ..

**Comment by bonomat** [comment]
close in favor of #872
