### ISSUE TITLE
Rejected positions clutter up the UI

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#556]
I find it irritating that rejected positions are displayed in the UI. I don't have any use for this information.

**Comment by klochowicz** [comment]
I think they should be filtered out by default (but still accessible if user wants to look at them). Some goes for the completed ones really, but it happens that they at the bottom, so they're less troublesome.

**Comment by thomaseizinger** [comment]
I was thinking of doing this as part of housekeeping:

1. It is good to see when an order gets rejected, it shouldn't disappear immediately.
2. On housekeeping, we can set a flag on all rejected orders to hide them in the UI.

Thoughts?

**Comment by da-kami** [comment]
I would optimize this at a later point. I don't think it is a good idea to remove such kind of information from the UI completely, because it is confusing as well. A user might remember that he clicked buy more than once, but the Cfd is "just gone" after restart without having any information what happened. 

We could put this information into a "hidden" section that can be unfolded. But I am not sure we need this optimization just yet.
This problem was mostly annoying because we kept running into `Rejected` scenarios because of #550 - which is fixed now. I would opt for tackling this problem once it becomes a problem again.

**Comment by bonomat** [comment]
I opted for not cleaning up the positions but cleaning up the presentation a bit, i.e. by default closed positions are not shown. 
see #662
