### ISSUE TITLE
Allow running taker with limited functionality without the maker online

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#623]
Some functions should be still possible when the user cannot connect to the maker.

For example:
- withdrawing funds,
- checking the status of the open/closed CFDs,
- closing a CFD

The UI should clearly indicate that only a subset of normal actions is possible and that there is no connection to the maker.

**Comment by da-kami** [comment]
I think at least withdrawing funds should be doable without the need of connecting to a maker for the Umbrel milestone already. 
Since we cannot easily "detach" that feature and need it in the UI for Umbrel - see #608 - I think this ticket needs to be on the milestone as well. I added it. @scratchscratchscratchy @itchymax
