### ISSUE TITLE
Re-design release process

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#735]
With the introduction of publishing docker images, our release process might need some refinements.

Originally, the idea was to publish pre-built binaries via releases and for that reason a `preview` release was introduced. However, this was more of a duct-tape solution than anything else as can be seen by the number of workarounds that we need to put in place for it to work correctly:

- https://github.com/itchysats/itchysats/pull/734
- https://github.com/itchysats/itchysats/blob/697771e71550b06148169e0c53fb2db20960670e/.github/workflows/preview-release.yml#L23

Both of these stem from the fact that tags are _meant_ to be immutable but our `preview` tag is not.

Unfortunately, the current process of releasing a `latest` docker image depends on the release binaries being built upon merges to master and attaching them to the `preview` release. The same workflow is also used to attach binaries to actual releases.

A re-designed process should take into account:

- No tag hacks like the above
- Ideally no duplication between workflows

Feature-wise, I think the bare minimum we need is:

- Updating the `latest` docker image every time we push to master
- Releasing a versioned docker tag upon releases (like 0.1.2)

With Umbrel becoming our main target user base, I think we can ditch attaching release binaries to releases.

Another thing that is currently not accounted for in our release process is doing releases from hotfix branches. Our automation for making a release there doesn't currently work because it always targets the master branch, regardless of which branch it was run from.

What would also be nice is if we would automatically tag an image with the minor version. i.e. releasing an image of version `0.3.6` should update the `0.3` tag so users can stay up to date with the latest compatible minor version without having to specify patch!

A major pain-point that I'd like to solve with this is that our current release process waits for all binaries to be built although for the docker images, we only need the linux binaries. In cases such as [this one](https://github.com/itchysats/itchysats/runs/5015035657?check_suite_focus=true), this resulted in a delay of 30 minutes until the change is deployed.

Thoughts welcome!

**Comment by thomaseizinger** [comment]
If we move the entire build process into the container, we could leverage `docker buildx` a bit better to build multi-platform images.

Couple of complications with that though:

- Our binaries embed the frontends
- If we build the binaries in the container, we need to also build the frontend in there - could use several multi-stage builds where we pass on the individual artifacts
- We could also build the frontends outside the container but then we need to pass it in somehow (`COPY?`)

Perhaps we should also look into splitting the `Dockerfile` into two (one `taker` one `maker`) given these differences in the build system ...

**Comment by bonomat** [comment]
> If we move the entire build process into the container, we could leverage `docker buildx` a bit better to build multi-platform images.

I tried exactly this last week but gave up because building inside the container is unbearably slow: 

1. `docker buildx` vs `github build matrix`: `buildx` parallelizes builds, but they are all in one action while building outside of a container can be parallelized using a build matrix
2. caching rust builds inside a container is really hard. I had a look at [cargo-chef](https://github.com/LukeMathWalker/cargo-chef/) but could not get it working probably. I'll attach the docker file further down below. The initial build [took over 3h](https://github.com/bonomat/hermes/runs/4329232493?check_suite_focus=true). 

cargo-chef dockerfile:
```
FROM lukemathwalker/cargo-chef:latest-rust-1.56.1 AS chef

LABEL "org.opencontainers.image.source"="https://github.com/itchysats/itchysats"
LABEL "org.opencontainers.image.authors"="hello@itchysats.network"

FROM chef AS planner

WORKDIR app
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM node:16 as frontend

ARG BINARY=taker

# Cache the frontend
WORKDIR /frontend
COPY $BINARY-frontend/package.json $BINARY-frontend/yarn.lock ./
RUN yarn

# Build the frontend
COPY $BINARY-frontend ./
RUN yarn build

FROM chef AS builder

ARG BINARY=taker

WORKDIR /app

# Copy dependency graph
COPY --from=planner /app/recipe.json recipe.json

# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json

COPY . .

# Copy frontend build artifacts
COPY --from=frontend /frontend/dist/$BINARY $BINARY-frontend/dist/$BINARY

# Build application
RUN cargo build --release --bin $BINARY


FROM gcr.io/distroless/cc

USER 1000

ARG BINARY=taker

COPY --from=builder /app/target/release/$BINARY /usr/local/bin/app

VOLUME data

# HTTP Port and P2P Port
EXPOSE 8000 9999

ENTRYPOINT ["/usr/local/bin/app", "--data-dir=/data", "--http-address=0.0.0.0:8000"]
```

**Comment by bonomat** [comment]
I would keep a similar build pipeline as we have right now: If we don't want the _preview-release process_ then we could duplicate the [build matrix](https://github.com/itchysats/itchysats/blob/6050be6b88f7a75926a1e59a272d3471ed39e333/.github/workflows/build-release-binary.yml#L8) and instead of publishing the resulting binaries as a release, we could upload them as artifacts to the build and then download them again in our docker image build, e.g.: 

```
jobs:
  build_binaries:
   strategy:
      matrix:
.... build binaries and upload as artifacts
  build_docker:
    needs: build_binaries
.... same as now but downloads from artifacts
``` 

The downside is that we would need to duplicate parts of the build logic (`yarn build` and `cargo build`). 
The advantage of this approach compared to building inside the docker container is that we can make use of parallel builds and cache the dependencies efficiently.

**Comment by thomaseizinger** [comment]
I came to the same conclusion and started some work here: https://github.com/itchysats/itchysats/pull/766/files

I think upload/download artifact is a good way of going about this! What I don't yet know is whether or not we can consolidate all binaries from a build matrix into one follow-up job.

**Comment by thomaseizinger** [comment]
Another thing that is currently not accounted for in our release process is doing releases from hotfix branches. Our automation for making a release there doesn't currently work because it always targets the master branch, regardless of which branch it was run from.
