### ISSUE TITLE
Unrealized P/L sometimes not refreshed correctly / outdated

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#848]
I think this might be related to being somehow detached from the feed. Not 100% sure though.

I noticed, that sometimes the displayed P/L does not change correctly according to the price changing. It is outdated.
After refreshing the page it changes.

Unfortunately I was unable to record a screenshot so far to proof it. 

Here is before the refresh:

![Screen Shot 2021-12-09 at 1 28 46 pm](https://user-images.githubusercontent.com/5557790/145324402-1ecafa14-5f9b-4a25-8a5d-41a6299c46c7.png)

After the refresh:

![Screen Shot 2021-12-09 at 1 28 59 pm](https://user-images.githubusercontent.com/5557790/145324432-c1e5bcfd-8d9d-41b8-af28-688c3256d724.png)

The daemon was running the whole time. I think somehow the feed got disconnected, hard to say why though.

I think we should prioritize #482 so we finally get knowledge about the UI feed being disconnected and not just using the `/alive` endpoint. That way the user at least can get a warning to refresh...
Given that a refresh fixed the issue I don't think it can be anything else.

**Comment by da-kami** [comment]
Another note: I just noticed that this happened only for one CFD! - the other one is up to date. Maybe the problem is actually in the UI, as in, React does not notice something changes (even though it did...) and does not refresh it? 
Would not know how that can be though

**Comment by da-kami** [comment]
Possible explanation of this problem: 
Since we have discetized intervals it can happen that on a price change one CFD's P/L changes whereas another CFD does not.
So, in our case the first CFD used a different payout interval upon price change, whereas for the second CFD for the same price change the same interval was still valid.

**Comment by klochowicz** [comment]
Hi, I am running into this problem running Umbrel. At first I thought it might be caused by the payout curve range, however it seems to not be the case. Price of BTC against USD jumped by 5% and I haven't seen any difference (!)

I took a couple of screenshots before I restarted Umbrel and after it. The difference in payout was significant (losing vs winning 😁  ):

before the restart:
![Screen Shot 2021-12-22 at 10 00 49 am](https://user-images.githubusercontent.com/8319440/147011683-470169f3-dae8-4445-a360-d976bcb59570.png)

after restart:
![Screen Shot 2021-12-22 at 10 07 58 am](https://user-images.githubusercontent.com/8319440/147011680-74da31c7-57f4-4655-a767-728fa65f0db4.png)

**Comment by klochowicz** [comment]
I suspect in my case I've lost connection to the underlying feeds (which is harder to spot, when the index price was still being updated). Hopefully this issue will give us more indication when we run into such problem:
https://github.com/itchysats/itchysats/issues/482

**Comment by bonomat** [comment]
This is quite old and might have been fixed already.
