### ISSUE TITLE
Http API for walletinfo

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#898]
In addition to getting CFDs via Http Get, it would be useful to have an endpoint to get the wallet info via Http Get. 

It's mostly aimed at simplifying things for the **maker** as one does not need to subscribe to the event source.

**Comment by thomaseizinger** [comment]
Is this for both daemons? We can add it if really needed but I just want to mention that because we are always sending the latest state via the SSE feed (and not deltas), it should be pretty easy to write a client that is always up to date with the latest data.

If we were only sending deltas, then this would be a different story because then being up to date requires reasoning about the state transitions over time. We always send the latest state which is exactly the same as the the response in any GET request.

This usecase _should_ be covered by our feeds so I am surprised that there is a need for it. We also always send the current state upon connecting to the feed to technically, the GET endpoint you are asking for already exists: GET the feed and wait for the wallet-info event.

Same things goes for the list of CFDs btw.

**Comment by bonomat** [comment]
It's aimed at the maker only. I've updated the description.

Of course you can build everything with SSE feed, it just adds another layer of complexity which I try to avoid. 
SSE is also harder to implement then just polling every now and then. 

One use I had already was quickly checking the balance in the wallet outside of any application. You can do this with HTTP Get but not with SSE, i.e. opening http://localhost:8001/api/feed in the browser does not give you anything useful

**Comment by thomaseizinger** [comment]
> You can do this with HTTP Get but not with SSE, i.e. opening http://localhost:8001/api/feed in the browser does not give you anything useful

curl supports SSE without issues but yeah, in the browser might be a bit of an issue.

> Of course you can build everything with SSE feed, it just adds another layer of complexity which I try to avoid. SSE is also harder to implement then just polling every now and then.

I don't understand why it is more complex. Do you want your client to not be reactive to state changes? **Polling** seems unnecessarily complex when you can get the last state pushed into your application.

But in any case, I am happy to add it to the maker binary!

**Comment by thomaseizinger** [comment]
I think this will be superseded with #1331 as long as we expose a balance metric.
