### ISSUE TITLE
Re-design usage of quotes / prices

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#946]
Currently, we [subscribe](https://github.com/itchysats/itchysats/blob/f5b135f9000cfaf3db3fabf55bc81445e3bec68f/daemon/src/bitmex_price_feed.rs#L17) to BitMex for quotes.

The latest quote is used for:

1. New offers on the maker side
2. Calculating unrealized P/L of open positions
3. Suggesting a price during collaborative settlement

(1) is problematic because when to trigger a a new offer is external to the maker binary and influenced by several things **including** a significant change in the current price. It would be a lot more natural to have the actual price of the offer also be external to the maker binary.
(2) is just wrong, we should use the index price for this.
(3) is tricky. We don't want to put this on the user and offer them an input field.

Would it be correct to suggest settling based on the current index price @bonomat @da-kami @itchymax @scratchscratchscratchy?

If yes, then we could do the following:

1. Swap the subscription URL to use the index price instead of bid/ask from the current order book.
2. Use that price to calculate P/L
3. Change the `new offer` endpoint to require a price (and remove the price subscription entirely from the maker).[^1]

[^1]: This implies that we are no longer doing any P/L calculation for the maker which is currently happening within `crate::projection` and used by _both_ parties. For now, we can just permanently pass `None` here for the maker but in the long run, these models should likely just separate and we need to projection modules, one for each binary.

**Comment by 1010Tom** [comment]
Thanks for writing this up. 

I agree with (1).

On 
>  (2) Calculating unrealized P/L of open positions
>  (3) Suggesting a price during collaborative settlement

In my eyes there are two ways how a position can be closed: 
1. Market order
2. Limited order

Let's focus only on (1) for now, which is what we have at the moment and leave (2) for the future.

Our collaborative settlement can be seen as closing with a _market order_ as the user is not asked for any input. 
He basically opens a position with the same amounts in the other direction and both positions get voided out. 
That being said, he would not get the current index price but the current market price (bid/ask). 

The important thing here is that the _unrealized P/L_ as shown in the UI is not equal to what he would get. It's an estimate if the position was to closed at the current price. 

For me this would mean two things: 

1. unrealized P/L is calculated using the index price, and
2. for collaborative closing the current _market price_ is taken. 

Ideally, *a* maker comes up with the price but that's a bit challenging because for us the maker we _market sell_ to is always the same we opened the position with in the first place. 
We should keep that in mind for the future. For now, I would take the current bid/ask rates for collaboratively closing.

**Comment by thomaseizinger** [comment]
> For now, I would take the current bid/ask rates for collaboratively closing.

That is tricky to as it would require us to track two different prices. Bid/ask and index. I was hoping to get away with only tracking one of the two within the taker binary for simplicity.
