### ISSUE TITLE
Provide seed as argument

### ISSUE THREAD

**Issue by 1010Tom** [itchysats/itchysats#978]
Umbrel exposes `$APP_SEED` which is a hex hex string deterministically derived from the users Umbrel seed. We could make use of this. It would mean that if a user's Umbrel broke and they setup a new one and imported their previous Umbrel seed, the ItchySats app would then derive the same wallet as the previous install and recover the previous funds.

_Originally posted by @lukechilds in https://github.com/getumbrel/umbrel/issues/1149#issuecomment-1001552559_

**Comment by thomaseizinger** [comment]
Do we even need https://github.com/itchysats/itchysats/pull/944 then? Seems unnecessary to have two mechanisms for this.

A non-umbrel user can already backup the current seed file and for umbrel, we can make use of `APP_SEED`. To make this easier to implement, I want to split it into two binaries otherwise we have too much conditional setup logic.

**Comment by thomaseizinger** [comment]
I've created https://github.com/itchysats/itchysats/issues/984 for this so that this is tracked explicitly.

**Comment by bonomat** [comment]
A few notes: 

- old users need to manually upgrade:
  1. close all positions
  2. withdraw funds
  3. upgrade and deposit funds 
- for this feature we won't need #944 anymore because we don't expect users to manage two backups
- we should implement this onto 0.3.x now and then reimplement it on master
